/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-6-24: 22h:57m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .h files for avr */
#ifdef _ATS_AVR
#include "ats/basics.h"
#endif /* _ATS_AVR */
/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_0 ;

typedef
struct {
ats_ptr_type atslab_s2exp_srt ;
ats_ptr_type atslab_s2exp_node ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_3 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2Eint_0) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2Eintinf_1) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_compare_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_int_type, _2opt_2postiats_2src_2pats_intinf_2esats__compare_intinf_int) (ats_ptr_type, ats_int_type) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2cstmap_add) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst) (ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neg_bool) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_add_bool_bool) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_mul_bool_bool) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_eq_bool_bool) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neq_bool_bool) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neg_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_add_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sub_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_mul_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_div_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_ndiv_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_idiv_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_lt_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_lte_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_gt_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_gte_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_eq_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neq_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_abs_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_absrel_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sgn_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sgnrel_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_max_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_min_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_maxrel_int_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_minrel_int_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_ndivrel_int_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_idivrel_int_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_ifint_bool_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_ifintrel_bool_int_int_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_int_of_addr) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_addr_of_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_lt_addr_addr) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_lte_addr_addr) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_gt_addr_addr) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_gte_addr_addr) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_eq_addr_addr) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neq_addr_addr) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_add_addr_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sub_addr_int) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sub_addr_addr) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_stacst2_2esats__s2exp_ineg) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_bneg) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_beq) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_bneq) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_badd) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_bmul) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ilt) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ilte) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_igt) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_igte) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ieq) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ineq) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ineg) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_iadd) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_isub) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_imul) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s2vbcfenv_replace_cstapp) (ats_ref_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make) (ats_ref_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type f_identity_0 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_neg_bool_1 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_add_bool_bool_2 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_mul_bool_bool_3 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_eq_bool_bool_4 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_neq_bool_bool_5 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_neg_int_6 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_add_int_int_7 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_sub_int_int_8 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_mul_int_int_9 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_ndiv_int_int_10 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_idiv_int_int_11 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_lt_int_int_12 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_lte_int_int_13 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_gt_int_int_14 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_gte_int_int_15 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_eq_int_int_16 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_neq_int_int_17 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_abs_int_18 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_sgn_int_19 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_max_int_int_20 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_min_int_int_21 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_ifint_bool_int_int_22 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type ins_24 (ats_ref_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 1656(line=55, offs=5) -- 1786(line=61, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_identity_0 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab_f_identity_0:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 1725(line=58, offs=7) -- 1754(line=58, offs=36)") ; }
tmp1 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp0 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp1) ;
return (tmp0) ;
} /* end of [f_identity_0] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 1854(line=65, offs=5) -- 2013(line=72, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_neg_bool_1 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab_f_neg_bool_1:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 1923(line=68, offs=7) -- 1951(line=68, offs=35)") ; }
tmp3 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp4 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp3) ;
tmp2 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_bneg (tmp4) ;
return (tmp2) ;
} /* end of [f_neg_bool_1] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 2044(line=74, offs=5) -- 2293(line=83, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_add_bool_bool_2 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;

__ats_lab_f_add_bool_bool_2:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 2119(line=77, offs=7) -- 2148(line=77, offs=36)") ; }
tmp6 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp7 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp7 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 2155(line=78, offs=7) -- 2184(line=78, offs=36)") ; }
tmp8 = ats_caselptrlab_mac(anairiats_sum_0, tmp7, atslab_0) ;
tmp9 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp6) ;
tmp10 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp8) ;
tmp5 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_badd (tmp9, tmp10) ;
return (tmp5) ;
} /* end of [f_add_bool_bool_2] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 2329(line=85, offs=5) -- 2578(line=94, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_mul_bool_bool_3 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;

__ats_lab_f_mul_bool_bool_3:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 2404(line=88, offs=7) -- 2433(line=88, offs=36)") ; }
tmp12 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp13 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp13 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 2440(line=89, offs=7) -- 2469(line=89, offs=36)") ; }
tmp14 = ats_caselptrlab_mac(anairiats_sum_0, tmp13, atslab_0) ;
tmp15 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp12) ;
tmp16 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp14) ;
tmp11 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_bmul (tmp15, tmp16) ;
return (tmp11) ;
} /* end of [f_mul_bool_bool_3] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 2614(line=96, offs=5) -- 2861(line=105, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_eq_bool_bool_4 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;

__ats_lab_f_eq_bool_bool_4:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 2688(line=99, offs=7) -- 2717(line=99, offs=36)") ; }
tmp18 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp19 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp19 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 2724(line=100, offs=7) -- 2753(line=100, offs=36)") ; }
tmp20 = ats_caselptrlab_mac(anairiats_sum_0, tmp19, atslab_0) ;
tmp21 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp18) ;
tmp22 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp20) ;
tmp17 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_beq (tmp21, tmp22) ;
return (tmp17) ;
} /* end of [f_eq_bool_bool_4] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 2896(line=107, offs=5) -- 3145(line=116, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_neq_bool_bool_5 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;

__ats_lab_f_neq_bool_bool_5:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 2971(line=110, offs=7) -- 3000(line=110, offs=36)") ; }
tmp24 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp25 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp25 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 3007(line=111, offs=7) -- 3036(line=111, offs=36)") ; }
tmp26 = ats_caselptrlab_mac(anairiats_sum_0, tmp25, atslab_0) ;
tmp27 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp24) ;
tmp28 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp26) ;
tmp23 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_bneq (tmp27, tmp28) ;
return (tmp23) ;
} /* end of [f_neq_bool_bool_5] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 3220(line=120, offs=5) -- 3383(line=127, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_neg_int_6 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;

__ats_lab_f_neg_int_6:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 3289(line=123, offs=7) -- 3318(line=123, offs=36)") ; }
tmp30 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp31 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp30) ;
tmp29 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ineg (tmp31) ;
return (tmp29) ;
} /* end of [f_neg_int_6] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 3413(line=129, offs=5) -- 3660(line=138, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_add_int_int_7 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;

__ats_lab_f_add_int_int_7:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 3486(line=132, offs=7) -- 3515(line=132, offs=36)") ; }
tmp33 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp34 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp34 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 3522(line=133, offs=7) -- 3551(line=133, offs=36)") ; }
tmp35 = ats_caselptrlab_mac(anairiats_sum_0, tmp34, atslab_0) ;
tmp36 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp33) ;
tmp37 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp35) ;
tmp32 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_iadd (tmp36, tmp37) ;
return (tmp32) ;
} /* end of [f_add_int_int_7] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 3694(line=140, offs=5) -- 3941(line=149, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_sub_int_int_8 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;

__ats_lab_f_sub_int_int_8:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 3767(line=143, offs=7) -- 3796(line=143, offs=36)") ; }
tmp39 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp40 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp40 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 3803(line=144, offs=7) -- 3832(line=144, offs=36)") ; }
tmp41 = ats_caselptrlab_mac(anairiats_sum_0, tmp40, atslab_0) ;
tmp42 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp39) ;
tmp43 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp41) ;
tmp38 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_isub (tmp42, tmp43) ;
return (tmp38) ;
} /* end of [f_sub_int_int_8] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 3975(line=151, offs=5) -- 4222(line=160, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_mul_int_int_9 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;

__ats_lab_f_mul_int_int_9:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 4048(line=154, offs=7) -- 4077(line=154, offs=36)") ; }
tmp45 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp46 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp46 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 4084(line=155, offs=7) -- 4113(line=155, offs=36)") ; }
tmp47 = ats_caselptrlab_mac(anairiats_sum_0, tmp46, atslab_0) ;
tmp48 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp45) ;
tmp49 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp47) ;
tmp44 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_imul (tmp48, tmp49) ;
return (tmp44) ;
} /* end of [f_mul_int_int_9] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 4256(line=162, offs=5) -- 4466(line=170, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_ndiv_int_int_10 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;

__ats_lab_f_ndiv_int_int_10:
tmp51 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2opt_2postiats_2src_2pats_stacst2_2esats__the_ndivrel_int_int_int) ;
tmp52 = _2opt_2postiats_2src_2pats_constraint3_2esats__s2vbcfenv_replace_cstapp (arg0, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int, tmp51, arg1) ;
tmp50 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_var (tmp52) ;
return (tmp50) ;
} /* end of [f_ndiv_int_int_10] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 4498(line=171, offs=5) -- 5369(line=201, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_idiv_int_int_11 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_int_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_int_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_bool_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_bool_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_bool_type, tmp70) ;

__ats_lab_f_idiv_int_int_11:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 4590(line=175, offs=7) -- 4619(line=175, offs=36)") ; }
tmp54 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp55 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp55 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 4626(line=176, offs=7) -- 4655(line=176, offs=36)") ; }
tmp56 = ats_caselptrlab_mac(anairiats_sum_0, tmp55, atslab_0) ;
tmp58 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp56), atslab_s2exp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp58)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp59 = ats_caselptrlab_mac(anairiats_sum_2, tmp58, atslab_0) ;
tmp57 = atspre_compare_int_int (tmp59, 0) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)tmp58)->tag != 1) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp60 = ats_caselptrlab_mac(anairiats_sum_3, tmp58, atslab_0) ;
tmp57 = _2opt_2postiats_2src_2pats_intinf_2esats__compare_intinf_int (tmp60, 0) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
__ats_lab_2_1:
tmp57 = 0 ;
break ;
} while (0) ;
tmp62 = atspre_neq_int_int (tmp57, 0) ;
if (tmp62) {
tmp61 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2opt_2postiats_2src_2pats_stacst2_2esats__the_ndivrel_int_int_int) ;
} else {
tmp61 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2opt_2postiats_2src_2pats_stacst2_2esats__the_idivrel_int_int_int) ;
} /* end of [if] */
tmp64 = atspre_gte_int_int (tmp57, 0) ;
if (tmp64) {
tmp63 = arg1 ;
} else {
tmp66 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2exp_ineg (tmp56) ;
tmp67 = (ats_sum_ptr_type)0 ;
tmp65 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp65, atslab_0, tmp66) ;
ats_selptrset_mac(anairiats_sum_0, tmp65, atslab_1, tmp67) ;
tmp63 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp63, atslab_0, tmp54) ;
ats_selptrset_mac(anairiats_sum_0, tmp63, atslab_1, tmp65) ;
} /* end of [if] */
tmp68 = _2opt_2postiats_2src_2pats_constraint3_2esats__s2vbcfenv_replace_cstapp (arg0, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int, tmp61, tmp63) ;
tmp69 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_var (tmp68) ;
tmp70 = atspre_gte_int_int (tmp57, 0) ;
if (tmp70) {
tmp53 = tmp69 ;
} else {
tmp53 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ineg (tmp69) ;
} /* end of [if] */
return (tmp53) ;
} /* end of [f_idiv_int_int_11] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 5404(line=203, offs=5) -- 5649(line=212, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_lt_int_int_12 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;

__ats_lab_f_lt_int_int_12:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 5476(line=206, offs=7) -- 5505(line=206, offs=36)") ; }
tmp72 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp73 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp73 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 5512(line=207, offs=7) -- 5541(line=207, offs=36)") ; }
tmp74 = ats_caselptrlab_mac(anairiats_sum_0, tmp73, atslab_0) ;
tmp75 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp72) ;
tmp76 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp74) ;
tmp71 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ilt (tmp75, tmp76) ;
return (tmp71) ;
} /* end of [f_lt_int_int_12] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 5682(line=214, offs=5) -- 5929(line=223, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_lte_int_int_13 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;

__ats_lab_f_lte_int_int_13:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 5755(line=217, offs=7) -- 5784(line=217, offs=36)") ; }
tmp78 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp79 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp79 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 5791(line=218, offs=7) -- 5820(line=218, offs=36)") ; }
tmp80 = ats_caselptrlab_mac(anairiats_sum_0, tmp79, atslab_0) ;
tmp81 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp78) ;
tmp82 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp80) ;
tmp77 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ilte (tmp81, tmp82) ;
return (tmp77) ;
} /* end of [f_lte_int_int_13] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 5963(line=225, offs=5) -- 6208(line=234, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_gt_int_int_14 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;

__ats_lab_f_gt_int_int_14:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 6035(line=228, offs=7) -- 6064(line=228, offs=36)") ; }
tmp84 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp85 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp85 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 6071(line=229, offs=7) -- 6100(line=229, offs=36)") ; }
tmp86 = ats_caselptrlab_mac(anairiats_sum_0, tmp85, atslab_0) ;
tmp87 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp84) ;
tmp88 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp86) ;
tmp83 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_igt (tmp87, tmp88) ;
return (tmp83) ;
} /* end of [f_gt_int_int_14] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 6241(line=236, offs=5) -- 6488(line=245, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_gte_int_int_15 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;

__ats_lab_f_gte_int_int_15:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 6314(line=239, offs=7) -- 6343(line=239, offs=36)") ; }
tmp90 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp91 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp91 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 6350(line=240, offs=7) -- 6379(line=240, offs=36)") ; }
tmp92 = ats_caselptrlab_mac(anairiats_sum_0, tmp91, atslab_0) ;
tmp93 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp90) ;
tmp94 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp92) ;
tmp89 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_igte (tmp93, tmp94) ;
return (tmp89) ;
} /* end of [f_gte_int_int_15] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 6522(line=247, offs=5) -- 6767(line=256, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_eq_int_int_16 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;

__ats_lab_f_eq_int_int_16:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 6594(line=250, offs=7) -- 6623(line=250, offs=36)") ; }
tmp96 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp97 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp97 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 6630(line=251, offs=7) -- 6659(line=251, offs=36)") ; }
tmp98 = ats_caselptrlab_mac(anairiats_sum_0, tmp97, atslab_0) ;
tmp99 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp96) ;
tmp100 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp98) ;
tmp95 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ieq (tmp99, tmp100) ;
return (tmp95) ;
} /* end of [f_eq_int_int_16] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 6800(line=258, offs=5) -- 7047(line=267, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_neq_int_int_17 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_ptr_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;

__ats_lab_f_neq_int_int_17:
if (arg1 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 6873(line=261, offs=7) -- 6902(line=261, offs=36)") ; }
tmp102 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp103 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
if (tmp103 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/opt/postiats/src/pats_constraint3_init.dats: 6909(line=262, offs=7) -- 6938(line=262, offs=36)") ; }
tmp104 = ats_caselptrlab_mac(anairiats_sum_0, tmp103, atslab_0) ;
tmp105 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp102) ;
tmp106 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_make (arg0, tmp104) ;
tmp101 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_ineq (tmp105, tmp106) ;
return (tmp101) ;
} /* end of [f_neq_int_int_17] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 7081(line=269, offs=5) -- 7281(line=276, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_abs_int_18 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;

__ats_lab_f_abs_int_18:
tmp108 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2opt_2postiats_2src_2pats_stacst2_2esats__the_absrel_int_int) ;
tmp109 = _2opt_2postiats_2src_2pats_constraint3_2esats__s2vbcfenv_replace_cstapp (arg0, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int, tmp108, arg1) ;
tmp107 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_var (tmp109) ;
return (tmp107) ;
} /* end of [f_abs_int_18] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 7311(line=278, offs=5) -- 7511(line=285, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_sgn_int_19 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;

__ats_lab_f_sgn_int_19:
tmp111 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2opt_2postiats_2src_2pats_stacst2_2esats__the_sgnrel_int_int) ;
tmp112 = _2opt_2postiats_2src_2pats_constraint3_2esats__s2vbcfenv_replace_cstapp (arg0, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int, tmp111, arg1) ;
tmp110 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_var (tmp112) ;
return (tmp110) ;
} /* end of [f_sgn_int_19] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 7541(line=287, offs=5) -- 7749(line=294, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_max_int_int_20 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;

__ats_lab_f_max_int_int_20:
tmp114 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2opt_2postiats_2src_2pats_stacst2_2esats__the_maxrel_int_int_int) ;
tmp115 = _2opt_2postiats_2src_2pats_constraint3_2esats__s2vbcfenv_replace_cstapp (arg0, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int, tmp114, arg1) ;
tmp113 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_var (tmp115) ;
return (tmp113) ;
} /* end of [f_max_int_int_20] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 7783(line=296, offs=5) -- 7991(line=303, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_min_int_int_21 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp116) ;
ATSlocal (ats_ptr_type, tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;

__ats_lab_f_min_int_int_21:
tmp117 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2opt_2postiats_2src_2pats_stacst2_2esats__the_minrel_int_int_int) ;
tmp118 = _2opt_2postiats_2src_2pats_constraint3_2esats__s2vbcfenv_replace_cstapp (arg0, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int, tmp117, arg1) ;
tmp116 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_var (tmp118) ;
return (tmp116) ;
} /* end of [f_min_int_int_21] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 8025(line=305, offs=5) -- 8247(line=312, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_ifint_bool_int_int_22 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;
ATSlocal (ats_ptr_type, tmp121) ;

__ats_lab_f_ifint_bool_int_int_22:
tmp120 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2opt_2postiats_2src_2pats_stacst2_2esats__the_ifintrel_bool_int_int_int) ;
tmp121 = _2opt_2postiats_2src_2pats_constraint3_2esats__s2vbcfenv_replace_cstapp (arg0, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int, tmp120, arg1) ;
tmp119 = _2opt_2postiats_2src_2pats_constraint3_2esats__s3exp_var (tmp121) ;
return (tmp119) ;
} /* end of [f_ifint_bool_int_int_22] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 8830(line=342, offs=5) -- 9076(line=351, offs=4)
*/
ATSstaticdec()
ats_void_type
ins_24 (ats_ref_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp123) ;
ATSlocal (ats_ptr_type, tmp124) ;
ATSlocal (ats_ptr_type, tmp125) ;
ATSlocal (ats_ptr_type, tmp126) ;

__ats_lab_ins_24:
tmp124 = _2opt_2postiats_2src_2pats_stacst2_2esats__s2cstref_get_cst (arg1) ;
tmp125 = ats_castfn_mac(ats_ptr_type, ats_ptrget_mac(ats_ptr_type, arg0)) ;
tmp126 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2cstmap_add (tmp125, tmp124, arg2) ;
ats_ptrget_mac(ats_ptr_type, arg0) = ats_castfn_mac(ats_ptr_type, tmp126) ;
return /* (tmp123) */ ;
} /* end of [ins_24] */

/*
// /opt/postiats/src/pats_constraint3_init.dats: 8756(line=338, offs=28) -- 11115(line=405, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_constraint3_2esats__constraint3_initialize_map (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp122) ;
// ATSlocal_void (tmp127) ;
// ATSlocal_void (tmp128) ;
// ATSlocal_void (tmp129) ;
// ATSlocal_void (tmp130) ;
// ATSlocal_void (tmp131) ;
// ATSlocal_void (tmp132) ;
// ATSlocal_void (tmp133) ;
// ATSlocal_void (tmp134) ;
// ATSlocal_void (tmp135) ;
// ATSlocal_void (tmp136) ;
// ATSlocal_void (tmp137) ;
// ATSlocal_void (tmp138) ;
// ATSlocal_void (tmp139) ;
// ATSlocal_void (tmp140) ;
// ATSlocal_void (tmp141) ;
// ATSlocal_void (tmp142) ;
// ATSlocal_void (tmp143) ;
// ATSlocal_void (tmp144) ;
// ATSlocal_void (tmp145) ;
// ATSlocal_void (tmp146) ;
// ATSlocal_void (tmp147) ;
// ATSlocal_void (tmp148) ;
// ATSlocal_void (tmp149) ;
// ATSlocal_void (tmp150) ;
// ATSlocal_void (tmp151) ;
// ATSlocal_void (tmp152) ;
// ATSlocal_void (tmp153) ;
// ATSlocal_void (tmp154) ;
// ATSlocal_void (tmp155) ;
// ATSlocal_void (tmp156) ;
// ATSlocal_void (tmp157) ;
// ATSlocal_void (tmp158) ;
// ATSlocal_void (tmp159) ;

__ats_lab__2opt_2postiats_2src_2pats_constraint3_2esats__constraint3_initialize_map:
/* tmp127 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neg_bool, &f_neg_bool_1) ;
/* tmp128 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_add_bool_bool, &f_add_bool_bool_2) ;
/* tmp129 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_mul_bool_bool, &f_mul_bool_bool_3) ;
/* tmp130 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_eq_bool_bool, &f_eq_bool_bool_4) ;
/* tmp131 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neq_bool_bool, &f_neq_bool_bool_5) ;
/* tmp132 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neg_int, &f_neg_int_6) ;
/* tmp133 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_add_int_int, &f_add_int_int_7) ;
/* tmp134 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sub_int_int, &f_sub_int_int_8) ;
/* tmp135 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_mul_int_int, &f_mul_int_int_9) ;
/* tmp136 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_div_int_int, &f_idiv_int_int_11) ;
/* tmp137 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_ndiv_int_int, &f_ndiv_int_int_10) ;
/* tmp138 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_idiv_int_int, &f_idiv_int_int_11) ;
/* tmp139 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_lt_int_int, &f_lt_int_int_12) ;
/* tmp140 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_lte_int_int, &f_lte_int_int_13) ;
/* tmp141 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_gt_int_int, &f_gt_int_int_14) ;
/* tmp142 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_gte_int_int, &f_gte_int_int_15) ;
/* tmp143 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_eq_int_int, &f_eq_int_int_16) ;
/* tmp144 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neq_int_int, &f_neq_int_int_17) ;
/* tmp145 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_abs_int, &f_abs_int_18) ;
/* tmp146 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sgn_int, &f_sgn_int_19) ;
/* tmp147 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_max_int_int, &f_max_int_int_20) ;
/* tmp148 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_min_int_int, &f_min_int_int_21) ;
/* tmp149 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_ifint_bool_int_int, &f_ifint_bool_int_int_22) ;
/* tmp150 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_int_of_addr, &f_identity_0) ;
/* tmp151 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_addr_of_int, &f_identity_0) ;
/* tmp152 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_add_addr_int, &f_add_int_int_7) ;
/* tmp153 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sub_addr_int, &f_sub_int_int_8) ;
/* tmp154 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_sub_addr_addr, &f_sub_int_int_8) ;
/* tmp155 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_lt_addr_addr, &f_lt_int_int_12) ;
/* tmp156 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_lte_addr_addr, &f_lte_int_int_13) ;
/* tmp157 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_gt_addr_addr, &f_gt_int_int_14) ;
/* tmp158 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_gte_addr_addr, &f_gte_int_int_15) ;
/* tmp159 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_eq_addr_addr, &f_eq_int_int_16) ;
/* tmp122 = */ ins_24 (arg0, _2opt_2postiats_2src_2pats_stacst2_2esats__the_neq_addr_addr, &f_neq_int_int_17) ;
return /* (tmp122) */ ;
} /* end of [_2opt_2postiats_2src_2pats_constraint3_2esats__constraint3_initialize_map] */

#ifdef _ATS_AVR

#define _2opt_2postiats_2src_2pats_constraint3_init_2edats__staload() 

#else

/* static load function */

// extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_intinf_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_stacst2_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_constraint3_2esats__staload (void) ;

ats_void_type
_2opt_2postiats_2src_2pats_constraint3_init_2edats__staload () {
static int _2opt_2postiats_2src_2pats_constraint3_init_2edats__staload_flag = 0 ;
if (_2opt_2postiats_2src_2pats_constraint3_init_2edats__staload_flag) return ;
_2opt_2postiats_2src_2pats_constraint3_init_2edats__staload_flag = 1 ;

// ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload () ;
_2opt_2postiats_2src_2pats_intinf_2esats__staload () ;
_2opt_2postiats_2src_2pats_staexp2_2esats__staload () ;
_2opt_2postiats_2src_2pats_stacst2_2esats__staload () ;
_2opt_2postiats_2src_2pats_constraint3_2esats__staload () ;

return ;
} /* staload function */


#endif/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2opt_2postiats_2src_2pats_constraint3_init_2edats__dynload_flag ;

ats_void_type
_2opt_2postiats_2src_2pats_constraint3_init_2edats__dynload () {
_2opt_2postiats_2src_2pats_constraint3_init_2edats__dynload_flag = 1 ;
_2opt_2postiats_2src_2pats_constraint3_init_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/opt/postiats/src/pats_constraint3_init_dats.c] */
