/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-6-24: 22h:57m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .h files for avr */
#ifdef _ATS_AVR
#include "ats/basics.h"
#endif /* _ATS_AVR */
/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_s2rtdat_sym ;
ats_ptr_type atslab_s2rtdat_sconlst ;
ats_int_type atslab_s2rtdat_stamp ;
} anairiats_rec_0 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_3 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_4 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2RTBASpre_0) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2RTBASimp_1) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2RTBASdef_2) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2RTbas_0) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2RTfun_1) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2RTtup_2) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2RTVar_3) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp2_2esats__S2RTerr_4) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_assert_errmsg) (ats_bool_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_newline) () ;
ATSextern_fun(ats_bool_type, atspre_neg_bool) (ats_bool_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_int) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_string) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_basics_2esats__test_fltkind) (ats_int_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_basics_2esats__test_boxkind) (ats_int_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_basics_2esats__test_linkind) (ats_int_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_basics_2esats__test_prfkind) (ats_int_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_basics_2esats__test_prgmkind) (ats_int_type) ;
ATSextern_fun(ats_int_type, _2opt_2postiats_2src_2pats_basics_2esats__test_polkind) (ats_int_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_basics_2esats__lte_impkind_impkind) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, _2opt_2postiats_2src_2pats_stamp_2esats__s2rtdat_stamp_make) () ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_INT) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_BOOL) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_ADDR) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_CHAR) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_CLS) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_EFF) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TKIND) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_PROP) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TYPE) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_T0YPE) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEW) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEWTYPE) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEWT0YPE) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TYPES) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_symbol_2esats__eq_symbol_symbol) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtdat_s2rtdat) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtVar_s2rtVar) (ats_ptr_type, ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_pos) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_neg) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_pos) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_neg) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_pos) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_neg) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_pos) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_neg) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_pos) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_neg) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_pos) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_neg) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_lin) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_boxed) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_tkind) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_set_s2rt) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_occurscheck) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_ptr_is_null) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_ptr_isnot_null) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_sort_2edats__lte_s2rtbas_s2rtbas) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rt_ltmat) (ats_int_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rtlst_ltmat) (ats_int_type, ats_ptr_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2opt_2postiats_2src_2pats_staexp2_2esats__sasp__s2rtVar = 0 ;
int _2opt_2postiats_2src_2pats_staexp2_2esats__sasp__s2rtdat_type = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_bool) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_addr) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_cls) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_eff) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_tkind) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_pos) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_neg) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_pos) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_neg) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_pos) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_neg) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_pos) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_neg) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_pos) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_neg) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_pos) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_neg) ;
ATSglobal(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_types) ;

/* internal function declarations */
static
ats_void_type prerr_interror_0 () ;
static
ats_ptr_type ptr_alloc_01234_anairiats_rec_0 () ;
static
ats_bool_type s2rt_test_fun_23 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type ref_01264_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type ref_make_elt_01265_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type aux_33 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_35 (ats_ptr_type arg0, ats_ref_type arg1) ;
static
ats_ptr_type auxlst_36 (ats_ptr_type arg0, ats_ref_type arg1) ;
static
ats_bool_type aux_39 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type aux_39_closure_make (ats_ptr_type env0) ;
static
ats_bool_type aux_39_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_bool_type auxlst_40 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type auxlst_40_closure_make (ats_ptr_type env0) ;
static
ats_bool_type auxlst_40_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_bool_type auxVar_46 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
ATSstatic (ats_ptr_type, statmp16) ;
ATSstatic (ats_ptr_type, statmp17) ;
ATSstatic (ats_ptr_type, statmp18) ;
ATSstatic (ats_ptr_type, statmp19) ;
ATSstatic (ats_ptr_type, statmp20) ;
ATSstatic (ats_ptr_type, statmp21) ;
ATSstatic (ats_ptr_type, statmp22) ;
ATSstatic (ats_ptr_type, statmp23) ;
ATSstatic (ats_ptr_type, statmp24) ;
ATSstatic (ats_ptr_type, statmp25) ;
ATSstatic (ats_ptr_type, statmp26) ;
ATSstatic (ats_ptr_type, statmp27) ;
ATSstatic (ats_ptr_type, statmp28) ;
ATSstatic (ats_ptr_type, statmp29) ;
ATSstatic (ats_ptr_type, statmp30) ;
ATSstatic (ats_ptr_type, statmp31) ;
ATSstatic (ats_ptr_type, statmp32) ;
ATSstatic (ats_ptr_type, statmp33) ;
ATSstatic (ats_ptr_type, statmp34) ;
ATSstatic (ats_ptr_type, statmp35) ;
ATSstatic (ats_ptr_type, statmp36) ;
ATSstatic (ats_ptr_type, statmp37) ;
ATSstatic (ats_ptr_type, statmp38) ;
ATSstatic (ats_ptr_type, statmp39) ;
ATSstatic (ats_ptr_type, statmp40) ;
ATSstatic (ats_ptr_type, statmp41) ;
ATSstatic (ats_ptr_type, statmp42) ;
ATSstatic (ats_ptr_type, statmp43) ;
ATSstatic (ats_ptr_type, statmp44) ;
ATSstatic (ats_ptr_type, statmp45) ;
ATSstatic (ats_ptr_type, statmp46) ;
ATSstatic (ats_ptr_type, statmp47) ;
ATSstatic (ats_ptr_type, statmp48) ;
ATSstatic (ats_ptr_type, statmp49) ;
ATSstatic (ats_ptr_type, statmp50) ;
ATSstatic (ats_ptr_type, statmp51) ;
ATSstatic (ats_ptr_type, statmp52) ;
ATSstatic (ats_ptr_type, statmp53) ;
ATSstatic (ats_ptr_type, statmp54) ;
ATSstatic (ats_ptr_type, statmp55) ;
ATSstatic (ats_ptr_type, statmp56) ;
ATSstatic (ats_ptr_type, statmp57) ;
ATSstatic (ats_ptr_type, statmp58) ;
ATSstatic (ats_ptr_type, statmp59) ;
ATSstatic (ats_ptr_type, statmp60) ;
ATSstatic (ats_ptr_type, statmp61) ;
ATSstatic (ats_ptr_type, statmp62) ;
ATSstatic (ats_ptr_type, statmp63) ;
ATSstatic (ats_ptr_type, statmp64) ;
ATSstatic (ats_ptr_type, statmp65) ;
ATSstatic (ats_ptr_type, statmp66) ;

/* external value variable declarations */

/* function implementations */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 1737(line=54, offs=5) -- 1798(line=54, offs=66)
*/
ATSstaticdec()
ats_void_type
prerr_interror_0 () {
/* local vardec */
// ATSlocal_void (tmp0) ;

__ats_lab_prerr_interror_0:
/* tmp0 = */ atspre_prerr_string (ATSstrcst("INTERROR(pats_staexp2_sort)")) ;
return /* (tmp0) */ ;
} /* end of [prerr_interror_0] */

/*
// /opt/ats0210/prelude/DATS/pointer.dats: 1817(line=56, offs=24) -- 1850(line=56, offs=57)
*/
ATSstaticdec()
ats_ptr_type
ptr_alloc_01234_anairiats_rec_0 () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab_ptr_alloc_01234_anairiats_rec_0:
tmp4 = atspre_ptr_alloc_tsz (sizeof(anairiats_rec_0)) ;
return (tmp4) ;
} /* end of [ptr_alloc_01234_anairiats_rec_0] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 2092(line=74, offs=14) -- 2407(line=86, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_make (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_int_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_make:
tmp2 = _2opt_2postiats_2src_2pats_stamp_2esats__s2rtdat_stamp_make () ;
tmp3 = ptr_alloc_01234_anairiats_rec_0 () ;
tmp5 = ats_selsin_mac(tmp3, atslab_2) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_0, tmp5), atslab_s2rtdat_sym) = arg0 ;
tmp6 = (ats_sum_ptr_type)0 ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_0, tmp5), atslab_s2rtdat_sconlst) = tmp6 ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_0, tmp5), atslab_s2rtdat_stamp) = tmp2 ;
tmp1 = atspre_ref_make_view_ptr (tmp5) ;
return (tmp1) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_make] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 2460(line=89, offs=17) -- 2540(line=91, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_sym (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_sym:
tmp8 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp7 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_0, tmp8), atslab_s2rtdat_sym) ;
return (tmp7) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_sym] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 2600(line=94, offs=21) -- 2684(line=96, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_sconlst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_sconlst:
tmp10 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp9 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_0, tmp10), atslab_s2rtdat_sconlst) ;
return (tmp9) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_sconlst] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 2747(line=98, offs=21) -- 2845(line=100, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_set_sconlst (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_set_sconlst:
tmp12 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
ats_selptr_mac(ats_castptr_mac(anairiats_rec_0, tmp12), atslab_s2rtdat_sconlst) = arg1 ;
return /* (tmp11) */ ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_set_sconlst] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 2907(line=103, offs=19) -- 2989(line=105, offs=4)
*/
ATSglobaldec()
ats_int_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_stamp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_stamp:
tmp14 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, arg0), atslab_1) ;
tmp13 = ats_selptr_mac(ats_castptr_mac(anairiats_rec_0, tmp14), atslab_s2rtdat_stamp) ;
return (tmp13) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtdat_get_stamp] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 3052(line=109, offs=3) -- 3134(line=111, offs=2)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtdat_s2rtdat (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp15) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtdat_s2rtdat:
tmp15 = atspre_peq (ats_castfn_mac(ats_ptr_type, arg0), ats_castfn_mac(ats_ptr_type, arg1)) ;
return (tmp15) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtdat_s2rtdat] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 6492(line=211, offs=13) -- 7358(line=247, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_impred (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp67) ;
// ATSlocal_void (tmp68) ;
// ATSlocal_void (tmp69) ;
// ATSlocal_void (tmp70) ;
// ATSlocal_void (tmp71) ;
// ATSlocal_void (tmp72) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_impred:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (arg0 != 5) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (arg0 != 0) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (arg0 != 1) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (arg0 != 7) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (arg0 != 2) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (arg0 != 3) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (arg0 != 13) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_pos ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (arg0 != 29) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_neg ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (arg0 != 8) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_pos ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (arg0 != 24) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_neg ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (arg0 != 9) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_pos ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (arg0 != 25) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_neg ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (arg0 != 15) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_pos ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (arg0 != 31) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_neg ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (arg0 != 10) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_pos ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (arg0 != 26) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_neg ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (arg0 != 11) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_pos ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (arg0 != 27) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_neg ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
__ats_lab_18_1:
/* tmp68 = */ prerr_interror_0 () ;
/* tmp69 = */ atspre_prerr_string (ATSstrcst(": s2rt_impred: knd = ")) ;
/* tmp70 = */ atspre_prerr_int (arg0) ;
/* tmp71 = */ atspre_prerr_newline () ;
/* tmp72 = */ atspre_assert_errmsg (ats_false_bool, "/opt/postiats/src/pats_staexp2_sort.dats: 7262(line=242, offs=14) -- 7278(line=242, offs=30)") ;
tmp67 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype ;
break ;
} while (0) ;
return (tmp67) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_impred] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 7450(line=254, offs=13) -- 7606(line=261, offs=15)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_int (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_int:
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_22_0 ; }
__ats_lab_19_1:
tmp74 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (((ats_sum_ptr_type)tmp74)->tag != 0) { goto __ats_lab_21_0 ; }
__ats_lab_20_1:
tmp75 = ats_caselptrlab_mac(anairiats_sum_1, tmp74, atslab_0) ;
tmp73 = _2opt_2postiats_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp75, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_INT) ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
__ats_lab_21_1:
tmp73 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
__ats_lab_22_1:
tmp73 = ats_false_bool ;
break ;
} while (0) ;
return (tmp73) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_int] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 7657(line=265, offs=14) -- 7814(line=272, offs=15)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_addr (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_addr:
do {
/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_26_0 ; }
__ats_lab_23_1:
tmp77 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)tmp77)->tag != 0) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp78 = ats_caselptrlab_mac(anairiats_sum_1, tmp77, atslab_0) ;
tmp76 = _2opt_2postiats_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp78, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_ADDR) ;
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
__ats_lab_25_1:
tmp76 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
__ats_lab_26_1:
tmp76 = ats_false_bool ;
break ;
} while (0) ;
return (tmp76) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_addr] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 7865(line=275, offs=14) -- 8020(line=282, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_bool (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_bool:
do {
/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_30_0 ; }
__ats_lab_27_1:
tmp80 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_28 */
__ats_lab_28_0:
if (((ats_sum_ptr_type)tmp80)->tag != 0) { goto __ats_lab_29_0 ; }
__ats_lab_28_1:
tmp81 = ats_caselptrlab_mac(anairiats_sum_1, tmp80, atslab_0) ;
tmp79 = _2opt_2postiats_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp81, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_BOOL) ;
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
__ats_lab_29_1:
tmp79 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
__ats_lab_30_1:
tmp79 = ats_false_bool ;
break ;
} while (0) ;
return (tmp79) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_bool] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 8071(line=286, offs=14) -- 8228(line=293, offs=15)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_char (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_char:
do {
/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_34_0 ; }
__ats_lab_31_1:
tmp83 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)tmp83)->tag != 0) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
tmp84 = ats_caselptrlab_mac(anairiats_sum_1, tmp83, atslab_0) ;
tmp82 = _2opt_2postiats_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp84, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_CHAR) ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
__ats_lab_33_1:
tmp82 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
__ats_lab_34_1:
tmp82 = ats_false_bool ;
break ;
} while (0) ;
return (tmp82) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_char] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 8278(line=297, offs=13) -- 8407(line=303, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_dat (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_dat:
do {
/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_38_0 ; }
__ats_lab_35_1:
tmp86 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (((ats_sum_ptr_type)tmp86)->tag != 2) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp85 = ats_true_bool ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
__ats_lab_37_1:
tmp85 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
__ats_lab_38_1:
tmp85 = ats_false_bool ;
break ;
} while (0) ;
return (tmp85) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_dat] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 8498(line=309, offs=13) -- 8553(line=311, offs=46)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_fun (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp87) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_fun:
do {
/* branch: __ats_lab_39 */
__ats_lab_39_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_40_0 ; }
__ats_lab_39_1:
tmp87 = ats_true_bool ;
break ;

/* branch: __ats_lab_40 */
__ats_lab_40_0:
__ats_lab_40_1:
tmp87 = ats_false_bool ;
break ;
} while (0) ;
return (tmp87) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_fun] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 8603(line=315, offs=13) -- 8757(line=322, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_prf (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_int_type, tmp90) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_prf:
do {
/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_44_0 ; }
__ats_lab_41_1:
tmp89 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_42 */
__ats_lab_42_0:
if (((ats_sum_ptr_type)tmp89)->tag != 1) { goto __ats_lab_43_0 ; }
__ats_lab_42_1:
tmp90 = ats_caselptrlab_mac(anairiats_sum_2, tmp89, atslab_0) ;
tmp88 = _2opt_2postiats_2src_2pats_basics_2esats__test_prfkind (tmp90) ;
break ;

/* branch: __ats_lab_43 */
__ats_lab_43_0:
__ats_lab_43_1:
tmp88 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_44 */
__ats_lab_44_0:
__ats_lab_44_1:
tmp88 = ats_false_bool ;
break ;
} while (0) ;
return (tmp88) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_prf] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 8821(line=326, offs=13) -- 8975(line=333, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_lin (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_int_type, tmp93) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_lin:
do {
/* branch: __ats_lab_45 */
__ats_lab_45_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_48_0 ; }
__ats_lab_45_1:
tmp92 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_46 */
__ats_lab_46_0:
if (((ats_sum_ptr_type)tmp92)->tag != 1) { goto __ats_lab_47_0 ; }
__ats_lab_46_1:
tmp93 = ats_caselptrlab_mac(anairiats_sum_2, tmp92, atslab_0) ;
tmp91 = _2opt_2postiats_2src_2pats_basics_2esats__test_linkind (tmp93) ;
break ;

/* branch: __ats_lab_47 */
__ats_lab_47_0:
__ats_lab_47_1:
tmp91 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_48 */
__ats_lab_48_0:
__ats_lab_48_1:
tmp91 = ats_false_bool ;
break ;
} while (0) ;
return (tmp91) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_lin] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 9042(line=337, offs=16) -- 9071(line=337, offs=45)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_nonlin (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp94) ;
ATSlocal (ats_bool_type, tmp95) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_nonlin:
tmp95 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_lin (arg0) ;
tmp94 = atspre_neg_bool (tmp95) ;
return (tmp94) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_nonlin] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 9098(line=340, offs=14) -- 9252(line=347, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_flat (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_int_type, tmp98) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_flat:
do {
/* branch: __ats_lab_49 */
__ats_lab_49_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_52_0 ; }
__ats_lab_49_1:
tmp97 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_50 */
__ats_lab_50_0:
if (((ats_sum_ptr_type)tmp97)->tag != 1) { goto __ats_lab_51_0 ; }
__ats_lab_50_1:
tmp98 = ats_caselptrlab_mac(anairiats_sum_2, tmp97, atslab_0) ;
tmp96 = _2opt_2postiats_2src_2pats_basics_2esats__test_fltkind (tmp98) ;
break ;

/* branch: __ats_lab_51 */
__ats_lab_51_0:
__ats_lab_51_1:
tmp96 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_52 */
__ats_lab_52_0:
__ats_lab_52_1:
tmp96 = ats_false_bool ;
break ;
} while (0) ;
return (tmp96) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_flat] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 9319(line=351, offs=15) -- 9473(line=358, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_boxed (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_int_type, tmp101) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_boxed:
do {
/* branch: __ats_lab_53 */
__ats_lab_53_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_56_0 ; }
__ats_lab_53_1:
tmp100 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_54 */
__ats_lab_54_0:
if (((ats_sum_ptr_type)tmp100)->tag != 1) { goto __ats_lab_55_0 ; }
__ats_lab_54_1:
tmp101 = ats_caselptrlab_mac(anairiats_sum_2, tmp100, atslab_0) ;
tmp99 = _2opt_2postiats_2src_2pats_basics_2esats__test_boxkind (tmp101) ;
break ;

/* branch: __ats_lab_55 */
__ats_lab_55_0:
__ats_lab_55_1:
tmp99 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_56 */
__ats_lab_56_0:
__ats_lab_56_1:
tmp99 = ats_false_bool ;
break ;
} while (0) ;
return (tmp99) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_boxed] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 9540(line=362, offs=14) -- 9695(line=369, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_prgm (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_int_type, tmp104) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_prgm:
do {
/* branch: __ats_lab_57 */
__ats_lab_57_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_60_0 ; }
__ats_lab_57_1:
tmp103 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_58 */
__ats_lab_58_0:
if (((ats_sum_ptr_type)tmp103)->tag != 1) { goto __ats_lab_59_0 ; }
__ats_lab_58_1:
tmp104 = ats_caselptrlab_mac(anairiats_sum_2, tmp103, atslab_0) ;
tmp102 = _2opt_2postiats_2src_2pats_basics_2esats__test_prgmkind (tmp104) ;
break ;

/* branch: __ats_lab_59 */
__ats_lab_59_0:
__ats_lab_59_1:
tmp102 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_60 */
__ats_lab_60_0:
__ats_lab_60_1:
tmp102 = ats_false_bool ;
break ;
} while (0) ;
return (tmp102) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_prgm] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 9763(line=373, offs=16) -- 9892(line=379, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_impred (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_impred:
do {
/* branch: __ats_lab_61 */
__ats_lab_61_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_64_0 ; }
__ats_lab_61_1:
tmp106 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_62 */
__ats_lab_62_0:
if (((ats_sum_ptr_type)tmp106)->tag != 1) { goto __ats_lab_63_0 ; }
__ats_lab_62_1:
tmp105 = ats_true_bool ;
break ;

/* branch: __ats_lab_63 */
__ats_lab_63_0:
__ats_lab_63_1:
tmp105 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_64 */
__ats_lab_64_0:
__ats_lab_64_1:
tmp105 = ats_false_bool ;
break ;
} while (0) ;
return (tmp105) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_impred] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 9982(line=385, offs=15) -- 10177(line=395, offs=13)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_tkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_tkind:
do {
/* branch: __ats_lab_65 */
__ats_lab_65_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_68_0 ; }
__ats_lab_65_1:
tmp108 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_66 */
__ats_lab_66_0:
if (((ats_sum_ptr_type)tmp108)->tag != 0) { goto __ats_lab_67_0 ; }
__ats_lab_66_1:
tmp109 = ats_caselptrlab_mac(anairiats_sum_1, tmp108, atslab_0) ;
tmp107 = _2opt_2postiats_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp109, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TKIND) ;
break ;

/* branch: __ats_lab_67 */
__ats_lab_67_0:
__ats_lab_67_1:
tmp107 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_68 */
__ats_lab_68_0:
__ats_lab_68_1:
tmp107 = ats_false_bool ;
break ;
} while (0) ;
return (tmp107) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_tkind] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 10253(line=402, offs=5) -- 10386(line=406, offs=2)
*/
ATSstaticdec()
ats_bool_type
s2rt_test_fun_23 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;

__ats_lab_s2rt_test_fun_23:
do {
/* branch: __ats_lab_69 */
__ats_lab_69_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_70_0 ; }
__ats_lab_69_1:
tmp111 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
arg0 = tmp111 ;
arg1 = arg1 ;
goto __ats_lab_s2rt_test_fun_23 ; // tail call
break ;

/* branch: __ats_lab_70 */
__ats_lab_70_0:
__ats_lab_70_1:
tmp110 = ((ats_bool_type(*)(ats_ptr_type))arg1) (arg0) ;
break ;
} while (0) ;
return (tmp110) ;
} /* end of [s2rt_test_fun_23] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 10465(line=412, offs=3) -- 10507(line=412, offs=45)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_boxed_fun (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp112) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_boxed_fun:
tmp112 = s2rt_test_fun_23 (arg0, &_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_boxed) ;
return (tmp112) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_boxed_fun] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 10569(line=417, offs=3) -- 10611(line=417, offs=45)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_tkind_fun (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp113) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_tkind_fun:
tmp113 = s2rt_test_fun_23 (arg0, &_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_tkind) ;
return (tmp113) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_is_tkind_fun] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 10710(line=425, offs=14) -- 10861(line=429, offs=11)
*/
ATSglobaldec()
ats_int_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_get_pol (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;
ATSlocal (ats_int_type, tmp116) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_get_pol:
do {
/* branch: __ats_lab_71 */
__ats_lab_71_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_74_0 ; }
__ats_lab_71_1:
tmp115 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
do {
/* branch: __ats_lab_72 */
__ats_lab_72_0:
if (((ats_sum_ptr_type)tmp115)->tag != 1) { goto __ats_lab_73_0 ; }
__ats_lab_72_1:
tmp116 = ats_caselptrlab_mac(anairiats_sum_2, tmp115, atslab_0) ;
tmp114 = _2opt_2postiats_2src_2pats_basics_2esats__test_polkind (tmp116) ;
break ;

/* branch: __ats_lab_73 */
__ats_lab_73_0:
__ats_lab_73_1:
tmp114 = 0 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_74 */
__ats_lab_74_0:
__ats_lab_74_1:
tmp114 = 0 ;
break ;
} while (0) ;
return (tmp114) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_get_pol] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 11564(line=466, offs=3) -- 11648(line=468, offs=2)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtVar_s2rtVar (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp117) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtVar_s2rtVar:
tmp117 = atspre_peq (ats_castfn_mac(ats_ptr_type, arg0), ats_castfn_mac(ats_ptr_type, arg1)) ;
return (tmp117) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtVar_s2rtVar] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 11717(line=472, offs=3) -- 11816(line=474, offs=2)
*/
ATSglobaldec()
ats_int_type
_2opt_2postiats_2src_2pats_staexp2_2esats__compare_s2rtVar_s2rtVar (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp118) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__compare_s2rtVar_s2rtVar:
tmp118 = atspre_compare_ptr_ptr (ats_castfn_mac(ats_ptr_type, arg0), ats_castfn_mac(ats_ptr_type, arg1)) ;
return (tmp118) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__compare_s2rtVar_s2rtVar] */

/*
// /opt/ats0210/prelude/DATS/reference.dats: 1828(line=57, offs=18) -- 1902(line=59, offs=4)
*/
ATSstaticdec()
ats_ptr_type
ref_01264_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp121) ;
ATSlocal (ats_ptr_type, tmp122) ;

__ats_lab_ref_01264_ats_ptr_type:
/* ats_ptr_type tmp122 ; */
tmp122 = arg0 ;
tmp121 = atspre_ref_make_elt_tsz ((&tmp122), sizeof(ats_ptr_type)) ;
return (tmp121) ;
} /* end of [ref_01264_ats_ptr_type] */

/*
// /opt/ats0210/prelude/DATS/reference.dats: 1994(line=62, offs=27) -- 2009(line=62, offs=42)
*/
ATSstaticdec()
ats_ptr_type
ref_make_elt_01265_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp120) ;

__ats_lab_ref_make_elt_01265_ats_ptr_type:
tmp120 = ref_01264_ats_ptr_type (arg0) ;
return (tmp120) ;
} /* end of [ref_make_elt_01265_ats_ptr_type] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 11898(line=479, offs=14) -- 11967(line=481, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_make (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp119) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_make:
tmp119 = ref_make_elt_01265_ats_ptr_type (ats_castfn_mac(ats_ptr_type, atspre_null_ptr)) ;
return (tmp119) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_make] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 12056(line=487, offs=7) -- 12428(line=501, offs=16)
*/
ATSstaticdec()
ats_ptr_type
aux_33 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp124) ;
ATSlocal (ats_ptr_type, tmp125) ;
ATSlocal (ats_ptr_type, tmp126) ;
ATSlocal (ats_bool_type, tmp127) ;
ATSlocal (ats_ptr_type, tmp128) ;

__ats_lab_aux_33:
do {
/* branch: __ats_lab_75 */
__ats_lab_75_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_76_0 ; }
__ats_lab_75_1:
tmp125 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp126 = ats_ptrget_mac(ats_ptr_type, tmp125) ;
tmp127 = atspre_ptr_isnot_null (tmp126) ;
if (tmp127) {
tmp128 = aux_33 (ats_castfn_mac(ats_ptr_type, tmp126)) ;
ats_ptrget_mac(ats_ptr_type, tmp125) = ats_castfn_mac(ats_ptr_type, tmp128) ;
tmp124 = tmp128 ;
} else {
tmp124 = arg0 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_76 */
__ats_lab_76_0:
__ats_lab_76_1:
tmp124 = arg0 ;
break ;
} while (0) ;
return (tmp124) ;
} /* end of [aux_33] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 12037(line=486, offs=13) -- 12480(line=505, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp123) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink:
tmp123 = aux_33 (arg0) ;
return (tmp123) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 12554(line=510, offs=7) -- 13388(line=540, offs=16)
*/
ATSstaticdec()
ats_ptr_type
aux_35 (ats_ptr_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;
ATSlocal (ats_ptr_type, tmp132) ;
ATSlocal (ats_int_type, tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;
ATSlocal (ats_ptr_type, tmp135) ;
ATSlocal (ats_bool_type, tmp136) ;
ATSlocal (ats_ptr_type, tmp137) ;
ATSlocal (ats_int_type, tmp138) ;
ATSlocal (ats_ptr_type, tmp139) ;
ATSlocal (ats_bool_type, tmp140) ;
ATSlocal (ats_ptr_type, tmp141) ;
ATSlocal (ats_ptr_type, tmp142) ;
ATSlocal (ats_bool_type, tmp143) ;
ATSlocal (ats_ptr_type, tmp144) ;
ATSlocal (ats_int_type, tmp145) ;

__ats_lab_aux_35:
do {
/* branch: __ats_lab_77 */
__ats_lab_77_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_78_0 ; }
__ats_lab_77_1:
tmp131 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp132 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp133 = ats_ptrget_mac(ats_int_type, arg1) ;
tmp134 = auxlst_36 (tmp131, arg1) ;
tmp135 = aux_35 (tmp132, arg1) ;
tmp136 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg1), tmp133) ;
if (tmp136) {
tmp130 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp130)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_3, tmp130, atslab_0, tmp134) ;
ats_selptrset_mac(anairiats_sum_3, tmp130, atslab_1, tmp135) ;
} else {
tmp130 = arg0 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_78 */
__ats_lab_78_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_79_0 ; }
__ats_lab_78_1:
tmp137 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp138 = ats_ptrget_mac(ats_int_type, arg1) ;
tmp139 = auxlst_36 (tmp137, arg1) ;
tmp140 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg1), tmp138) ;
if (tmp140) {
tmp130 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp130)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_1, tmp130, atslab_0, tmp139) ;
} else {
tmp130 = arg0 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_79 */
__ats_lab_79_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_80_0 ; }
__ats_lab_79_1:
tmp141 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp142 = ats_ptrget_mac(ats_ptr_type, tmp141) ;
tmp143 = atspre_ptr_isnot_null (tmp142) ;
if (tmp143) {
tmp144 = aux_35 (ats_castfn_mac(ats_ptr_type, tmp142), arg1) ;
ats_ptrget_mac(ats_ptr_type, tmp141) = ats_castfn_mac(ats_ptr_type, tmp144) ;
tmp145 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg1), 1) ;
ats_ptrget_mac(ats_int_type, arg1) = tmp145 ;
tmp130 = tmp144 ;
} else {
tmp130 = arg0 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_80 */
__ats_lab_80_0:
__ats_lab_80_1:
tmp130 = arg0 ;
break ;
} while (0) ;
return (tmp130) ;
} /* end of [aux_35] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 13419(line=543, offs=7) -- 13740(line=554, offs=33)
*/
ATSstaticdec()
ats_ptr_type
auxlst_36 (ats_ptr_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp146) ;
ATSlocal (ats_ptr_type, tmp147) ;
ATSlocal (ats_ptr_type, tmp148) ;
ATSlocal (ats_int_type, tmp149) ;
ATSlocal (ats_ptr_type, tmp150) ;
ATSlocal (ats_ptr_type, tmp151) ;
ATSlocal (ats_bool_type, tmp152) ;

__ats_lab_auxlst_36:
do {
/* branch: __ats_lab_81 */
__ats_lab_81_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_82_0 ; }
__ats_lab_81_1:
tmp147 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp148 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp149 = ats_ptrget_mac(ats_int_type, arg1) ;
tmp150 = aux_35 (tmp147, arg1) ;
tmp151 = auxlst_36 (tmp148, arg1) ;
tmp152 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg1), tmp149) ;
if (tmp152) {
tmp146 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
ats_selptrset_mac(anairiats_sum_4, tmp146, atslab_0, tmp150) ;
ats_selptrset_mac(anairiats_sum_4, tmp146, atslab_1, tmp151) ;
} else {
tmp146 = arg0 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_82 */
__ats_lab_82_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_82_1:
tmp146 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp146) ;
} /* end of [auxlst_36] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 12532(line=508, offs=17) -- 13816(line=561, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink_all (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp129) ;
ATSlocal (ats_int_type, tmp153) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink_all:
/* ats_int_type tmp153 ; */
tmp153 = 0 ;
tmp129 = aux_35 (arg0, (&tmp153)) ;
return (tmp129) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink_all] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 13894(line=566, offs=18) -- 13963(line=568, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_set_s2rt (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp154) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_set_s2rt:
ats_ptrget_mac(ats_ptr_type, arg0) = ats_castfn_mac(ats_ptr_type, arg1) ;
return /* (tmp154) */ ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_set_s2rt] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 14049(line=574, offs=5) -- 14514(line=591, offs=24)
*/
ATSstaticdec()
ats_bool_type
aux_39 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp156) ;
ATSlocal (ats_ptr_type, tmp157) ;
ATSlocal (ats_ptr_type, tmp158) ;
ATSlocal (ats_bool_type, tmp159) ;
ATSlocal (ats_ptr_type, tmp160) ;
ATSlocal (ats_ptr_type, tmp161) ;
ATSlocal (ats_bool_type, tmp162) ;
ATSlocal (ats_ptr_type, tmp163) ;
ATSlocal (ats_bool_type, tmp164) ;
ATSlocal (ats_ptr_type, tmp165) ;

__ats_lab_aux_39:
do {
/* branch: __ats_lab_83 */
__ats_lab_83_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_84_0 ; }
__ats_lab_83_1:
tmp156 = ats_false_bool ;
break ;

/* branch: __ats_lab_84 */
__ats_lab_84_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_85_0 ; }
__ats_lab_84_1:
tmp157 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp158 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp159 = auxlst_40 (env0, tmp157) ;
if (tmp159) {
tmp156 = ats_true_bool ;
} else {
arg0 = tmp158 ;
goto __ats_lab_aux_39 ; // tail call
} /* end of [if] */
break ;

/* branch: __ats_lab_85 */
__ats_lab_85_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_86_0 ; }
__ats_lab_85_1:
tmp160 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp156 = auxlst_40 (env0, tmp160) ;
break ;

/* branch: __ats_lab_86 */
__ats_lab_86_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_87_0 ; }
__ats_lab_86_1:
tmp161 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp162 = _2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtVar_s2rtVar (env0, tmp161) ;
if (tmp162) {
tmp156 = ats_true_bool ;
} else {
tmp163 = ats_ptrget_mac(ats_ptr_type, tmp161) ;
tmp164 = atspre_ptr_isnot_null (tmp163) ;
if (tmp164) {
tmp165 = ats_castfn_mac(ats_ptr_type, tmp163) ;
arg0 = tmp165 ;
goto __ats_lab_aux_39 ; // tail call
} else {
tmp156 = ats_false_bool ;
} /* end of [if] */
} /* end of [if] */
break ;

/* branch: __ats_lab_87 */
__ats_lab_87_0:
// if (((ats_sum_ptr_type)arg0)->tag != 4) { ats_deadcode_failure_handle () ; }
__ats_lab_87_1:
tmp156 = ats_false_bool ;
break ;
} while (0) ;
return (tmp156) ;
} /* end of [aux_39] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} aux_39_closure_type ;

ats_bool_type
aux_39_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return aux_39 (((aux_39_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
aux_39_closure_init (aux_39_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&aux_39_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
aux_39_closure_make (ats_ptr_type env0) {
aux_39_closure_type *p_clo = ATS_MALLOC(sizeof(aux_39_closure_type)) ;
aux_39_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 14522(line=593, offs=5) -- 14710(line=600, offs=25)
*/
ATSstaticdec()
ats_bool_type
auxlst_40 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp166) ;
ATSlocal (ats_ptr_type, tmp167) ;
ATSlocal (ats_ptr_type, tmp168) ;
ATSlocal (ats_bool_type, tmp169) ;

__ats_lab_auxlst_40:
do {
/* branch: __ats_lab_88 */
__ats_lab_88_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_89_0 ; }
__ats_lab_88_1:
tmp167 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp168 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp169 = aux_39 (env0, tmp167) ;
if (tmp169) {
tmp166 = ats_true_bool ;
} else {
arg0 = tmp168 ;
goto __ats_lab_auxlst_40 ; // tail call
} /* end of [if] */
break ;

/* branch: __ats_lab_89 */
__ats_lab_89_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_89_1:
tmp166 = ats_false_bool ;
break ;
} while (0) ;
return (tmp166) ;
} /* end of [auxlst_40] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} auxlst_40_closure_type ;

ats_bool_type
auxlst_40_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return auxlst_40 (((auxlst_40_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
auxlst_40_closure_init (auxlst_40_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&auxlst_40_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
auxlst_40_closure_make (ats_ptr_type env0) {
auxlst_40_closure_type *p_clo = ATS_MALLOC(sizeof(auxlst_40_closure_type)) ;
auxlst_40_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 14026(line=572, offs=3) -- 14733(line=604, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_occurscheck (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp155) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_occurscheck:
tmp155 = aux_39 (arg0, arg1) ;
return (tmp155) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_occurscheck] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 14850(line=613, offs=10) -- 14885(line=613, offs=45)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_fun (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp170) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_fun:
tmp170 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp170)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_3, tmp170, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_3, tmp170, atslab_1, arg1) ;
return (tmp170) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_fun] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 14906(line=616, offs=10) -- 14928(line=616, offs=32)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_tup (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp171) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_tup:
tmp171 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp171)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_1, tmp171, atslab_0, arg0) ;
return (tmp171) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_tup] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 14986(line=619, offs=10) -- 15001(line=619, offs=25)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_err () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp172) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_err:
tmp172 = (ats_sum_ptr_type)(&_2opt_2postiats_2src_2pats_staexp2_2esats__S2RTerr_4) ;
return (tmp172) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_err] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 15188(line=629, offs=21) -- 15466(line=636, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_sort_2edats__lte_s2rtbas_s2rtbas (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp173) ;
ATSlocal (ats_ptr_type, tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;
ATSlocal (ats_int_type, tmp176) ;
ATSlocal (ats_int_type, tmp177) ;
ATSlocal (ats_ptr_type, tmp178) ;
ATSlocal (ats_ptr_type, tmp179) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_sort_2edats__lte_s2rtbas_s2rtbas:
do {
/* branch: __ats_lab_90 */
__ats_lab_90_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_91_0 ; }
__ats_lab_90_1:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_93_1 ; }
__ats_lab_90_2:
tmp174 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp175 = ats_caselptrlab_mac(anairiats_sum_1, arg1, atslab_0) ;
tmp173 = _2opt_2postiats_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp174, tmp175) ;
break ;

/* branch: __ats_lab_91 */
__ats_lab_91_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_92_0 ; }
__ats_lab_91_1:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_93_1 ; }
__ats_lab_91_2:
tmp176 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp177 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
tmp173 = _2opt_2postiats_2src_2pats_basics_2esats__lte_impkind_impkind (tmp176, tmp177) ;
break ;

/* branch: __ats_lab_92 */
__ats_lab_92_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_93_0 ; }
__ats_lab_92_1:
if (((ats_sum_ptr_type)arg1)->tag != 2) { goto __ats_lab_93_1 ; }
__ats_lab_92_2:
tmp178 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp179 = ats_caselptrlab_mac(anairiats_sum_1, arg1, atslab_0) ;
tmp173 = _2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtdat_s2rtdat (tmp178, tmp179) ;
break ;

/* branch: __ats_lab_93 */
__ats_lab_93_0:
__ats_lab_93_1:
__ats_lab_93_2:
tmp173 = ats_false_bool ;
break ;
} while (0) ;
return (tmp173) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_sort_2edats__lte_s2rtbas_s2rtbas] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 15752(line=652, offs=7) -- 16023(line=662, offs=11)
*/
ATSstaticdec()
ats_bool_type
auxVar_46 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp181) ;
ATSlocal (ats_bool_type, tmp182) ;
ATSlocal (ats_bool_type, tmp183) ;
// ATSlocal_void (tmp184) ;

__ats_lab_auxVar_46:
tmp182 = atspre_gt_int_int (arg2, 0) ;
if (tmp182) {
tmp183 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_occurscheck (arg0, arg1) ;
if (tmp183) {
tmp181 = ats_false_bool ;
} else {
/* tmp184 = */ _2opt_2postiats_2src_2pats_staexp2_2esats__s2rtVar_set_s2rt (arg0, arg1) ;
tmp181 = ats_true_bool ;
} /* end of [if] */
} else {
tmp181 = ats_true_bool ;
} /* end of [if] */
return (tmp181) ;
} /* end of [auxVar_46] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 15719(line=650, offs=3) -- 16720(line=691, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rt_ltmat (ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp180) ;
ATSlocal (ats_ptr_type, tmp185) ;
ATSlocal (ats_ptr_type, tmp186) ;
ATSlocal (ats_ptr_type, tmp187) ;
ATSlocal (ats_ptr_type, tmp188) ;
ATSlocal (ats_ptr_type, tmp189) ;
ATSlocal (ats_ptr_type, tmp190) ;
ATSlocal (ats_ptr_type, tmp191) ;
ATSlocal (ats_ptr_type, tmp192) ;
ATSlocal (ats_bool_type, tmp193) ;
ATSlocal (ats_ptr_type, tmp194) ;
ATSlocal (ats_ptr_type, tmp195) ;
ATSlocal (ats_ptr_type, tmp196) ;
ATSlocal (ats_ptr_type, tmp197) ;
ATSlocal (ats_bool_type, tmp198) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rt_ltmat:
tmp185 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink (arg1) ;
tmp186 = _2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_delink (arg2) ;
do {
/* branch: __ats_lab_94 */
__ats_lab_94_0:
if (((ats_sum_ptr_type)tmp185)->tag != 0) { goto __ats_lab_97_0 ; }
__ats_lab_94_1:
tmp187 = ats_caselptrlab_mac(anairiats_sum_1, tmp185, atslab_0) ;
do {
/* branch: __ats_lab_95 */
__ats_lab_95_0:
if (((ats_sum_ptr_type)tmp186)->tag != 0) { goto __ats_lab_96_0 ; }
__ats_lab_95_1:
tmp188 = ats_caselptrlab_mac(anairiats_sum_1, tmp186, atslab_0) ;
tmp180 = _2opt_2postiats_2src_2pats_staexp2_sort_2edats__lte_s2rtbas_s2rtbas (tmp187, tmp188) ;
break ;

/* branch: __ats_lab_96 */
__ats_lab_96_0:
__ats_lab_96_1:
tmp180 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_97 */
__ats_lab_97_0:
if (((ats_sum_ptr_type)tmp185)->tag != 1) { goto __ats_lab_100_0 ; }
__ats_lab_97_1:
tmp189 = ats_caselptrlab_mac(anairiats_sum_3, tmp185, atslab_0) ;
tmp190 = ats_caselptrlab_mac(anairiats_sum_3, tmp185, atslab_1) ;
do {
/* branch: __ats_lab_98 */
__ats_lab_98_0:
if (((ats_sum_ptr_type)tmp186)->tag != 1) { goto __ats_lab_99_0 ; }
__ats_lab_98_1:
tmp191 = ats_caselptrlab_mac(anairiats_sum_3, tmp186, atslab_0) ;
tmp192 = ats_caselptrlab_mac(anairiats_sum_3, tmp186, atslab_1) ;
tmp193 = _2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rtlst_ltmat (arg0, tmp191, tmp189) ;
if (tmp193) {
arg0 = arg0 ;
arg1 = tmp190 ;
arg2 = tmp192 ;
goto __ats_lab__2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rt_ltmat ; // tail call
} else {
tmp180 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_99 */
__ats_lab_99_0:
__ats_lab_99_1:
tmp180 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_100 */
__ats_lab_100_0:
if (((ats_sum_ptr_type)tmp185)->tag != 2) { goto __ats_lab_103_0 ; }
__ats_lab_100_1:
tmp194 = ats_caselptrlab_mac(anairiats_sum_1, tmp185, atslab_0) ;
do {
/* branch: __ats_lab_101 */
__ats_lab_101_0:
if (((ats_sum_ptr_type)tmp186)->tag != 2) { goto __ats_lab_102_0 ; }
__ats_lab_101_1:
tmp195 = ats_caselptrlab_mac(anairiats_sum_1, tmp186, atslab_0) ;
tmp180 = _2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rtlst_ltmat (arg0, tmp194, tmp195) ;
break ;

/* branch: __ats_lab_102 */
__ats_lab_102_0:
__ats_lab_102_1:
tmp180 = ats_false_bool ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_103 */
__ats_lab_103_0:
if (((ats_sum_ptr_type)tmp185)->tag != 3) { goto __ats_lab_106_0 ; }
__ats_lab_103_1:
tmp196 = ats_caselptrlab_mac(anairiats_sum_1, tmp185, atslab_0) ;
do {
/* branch: __ats_lab_104 */
__ats_lab_104_0:
if (((ats_sum_ptr_type)tmp186)->tag != 3) { goto __ats_lab_105_0 ; }
__ats_lab_104_1:
tmp197 = ats_caselptrlab_mac(anairiats_sum_1, tmp186, atslab_0) ;
tmp198 = _2opt_2postiats_2src_2pats_staexp2_2esats__eq_s2rtVar_s2rtVar (tmp196, tmp197) ;
if (!tmp198) { goto __ats_lab_105_1 ; }
tmp180 = ats_true_bool ;
break ;

/* branch: __ats_lab_105 */
__ats_lab_105_0:
__ats_lab_105_1:
tmp180 = auxVar_46 (tmp196, tmp186, arg0) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_106 */
__ats_lab_106_0:
// if (((ats_sum_ptr_type)tmp185)->tag != 4) { ats_deadcode_failure_handle () ; }
__ats_lab_106_1:
tmp180 = ats_false_bool ;
break ;
} while (0) ;
return (tmp180) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rt_ltmat] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 16771(line=695, offs=3) -- 17001(line=700, offs=20)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rtlst_ltmat (ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp199) ;
ATSlocal (ats_ptr_type, tmp200) ;
ATSlocal (ats_ptr_type, tmp201) ;
ATSlocal (ats_ptr_type, tmp202) ;
ATSlocal (ats_ptr_type, tmp203) ;
ATSlocal (ats_bool_type, tmp204) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rtlst_ltmat:
do {
/* branch: __ats_lab_107 */
__ats_lab_107_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_108_0 ; }
__ats_lab_107_1:
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_109_1 ; }
__ats_lab_107_2:
tmp200 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_0) ;
tmp201 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_1) ;
tmp202 = ats_caselptrlab_mac(anairiats_sum_4, arg2, atslab_0) ;
tmp203 = ats_caselptrlab_mac(anairiats_sum_4, arg2, atslab_1) ;
tmp204 = _2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rt_ltmat (arg0, tmp200, tmp202) ;
if (tmp204) {
arg0 = arg0 ;
arg1 = tmp201 ;
arg2 = tmp203 ;
goto __ats_lab__2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rtlst_ltmat ; // tail call
} else {
tmp199 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_108 */
__ats_lab_108_0:
if (arg1 != (ats_sum_ptr_type)0) { goto __ats_lab_109_0 ; }
__ats_lab_108_1:
if (arg2 != (ats_sum_ptr_type)0) { goto __ats_lab_109_1 ; }
__ats_lab_108_2:
tmp199 = ats_true_bool ;
break ;

/* branch: __ats_lab_109 */
__ats_lab_109_0:
__ats_lab_109_1:
__ats_lab_109_2:
tmp199 = ats_false_bool ;
break ;
} while (0) ;
return (tmp199) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rtlst_ltmat] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 17074(line=705, offs=23) -- 17107(line=705, offs=56)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_ltmat0 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp205) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_ltmat0:
tmp205 = _2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rt_ltmat (0, arg0, arg1) ;
return (tmp205) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_ltmat0] */

/*
// /opt/postiats/src/pats_staexp2_sort.dats: 17130(line=706, offs=23) -- 17163(line=706, offs=56)
*/
ATSglobaldec()
ats_bool_type
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_ltmat1 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp206) ;

__ats_lab__2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_ltmat1:
tmp206 = _2opt_2postiats_2src_2pats_staexp2_sort_2edats__s2rt_ltmat (1, arg0, arg1) ;
return (tmp206) ;
} /* end of [_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_ltmat1] */

#ifdef _ATS_AVR

#define _2opt_2postiats_2src_2pats_staexp2_sort_2edats__staload() 

#else

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2pointer_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2reference_2edats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_stamp_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_symbol_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_staexp2_2esats__staload (void) ;

ats_void_type
_2opt_2postiats_2src_2pats_staexp2_sort_2edats__staload () {
static int _2opt_2postiats_2src_2pats_staexp2_sort_2edats__staload_flag = 0 ;
if (_2opt_2postiats_2src_2pats_staexp2_sort_2edats__staload_flag) return ;
_2opt_2postiats_2src_2pats_staexp2_sort_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e10_2prelude_2DATS_2pointer_2edats__staload () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2reference_2edats__staload () ;
_2opt_2postiats_2src_2pats_stamp_2esats__staload () ;
_2opt_2postiats_2src_2pats_symbol_2esats__staload () ;
_2opt_2postiats_2src_2pats_basics_2esats__staload () ;
_2opt_2postiats_2src_2pats_staexp2_2esats__staload () ;

return ;
} /* staload function */


#endif/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2opt_2postiats_2src_2pats_staexp2_sort_2edats__dynload_flag ;

ats_void_type
_2opt_2postiats_2src_2pats_staexp2_sort_2edats__dynload () {
_2opt_2postiats_2src_2pats_staexp2_sort_2edats__dynload_flag = 1 ;
_2opt_2postiats_2src_2pats_staexp2_sort_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */
ATS_GC_MARKROOT(&statmp16, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp17, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp18, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp19, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp20, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp21, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp22, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp23, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp24, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp25, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp26, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp27, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp28, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp29, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp30, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp31, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp32, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp33, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp34, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp35, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp36, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp37, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp38, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp39, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp40, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp41, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp42, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp43, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp44, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp45, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp46, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp47, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp48, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp49, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp50, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp51, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp52, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp53, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp54, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp55, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp56, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp57, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp58, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp59, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp60, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp61, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp62, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp63, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp64, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp65, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp66, sizeof(ats_ptr_type)) ;

/* marking external values for GC */

/* code for dynamic loading */
statmp16 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp16)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp16, atslab_0, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_INT) ;
statmp17 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp17)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp17, atslab_0, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_BOOL) ;
statmp18 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp18)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp18, atslab_0, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_ADDR) ;
statmp19 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp19)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp19, atslab_0, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_CHAR) ;
statmp20 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp20)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp20, atslab_0, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_CLS) ;
statmp21 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp21)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp21, atslab_0, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_EFF) ;
statmp22 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp22)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp22, atslab_0, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TKIND) ;
statmp23 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp23)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp23, atslab_0, statmp16) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_int = statmp23 ;
statmp24 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp24)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp24, atslab_0, statmp17) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_bool, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_bool = statmp24 ;
statmp25 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp25)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp25, atslab_0, statmp18) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_addr, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_addr = statmp25 ;
statmp26 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp26)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp26, atslab_0, statmp20) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_cls, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_cls = statmp26 ;
statmp27 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp27)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp27, atslab_0, statmp21) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_eff, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_eff = statmp27 ;
statmp28 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp28)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp28, atslab_0, statmp22) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_tkind, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_tkind = statmp28 ;
statmp29 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp29)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp29, atslab_0, 5) ;
ats_selptrset_mac(anairiats_sum_2, statmp29, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_PROP) ;
statmp30 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp30)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp30, atslab_0, 13) ;
ats_selptrset_mac(anairiats_sum_2, statmp30, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_PROP) ;
statmp31 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp31)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp31, atslab_0, 29) ;
ats_selptrset_mac(anairiats_sum_2, statmp31, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_PROP) ;
statmp32 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp32)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp32, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp32, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TYPE) ;
statmp33 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp33)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp33, atslab_0, 8) ;
ats_selptrset_mac(anairiats_sum_2, statmp33, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TYPE) ;
statmp34 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp34)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp34, atslab_0, 24) ;
ats_selptrset_mac(anairiats_sum_2, statmp34, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TYPE) ;
statmp35 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp35)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp35, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp35, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_T0YPE) ;
statmp36 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp36)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp36, atslab_0, 9) ;
ats_selptrset_mac(anairiats_sum_2, statmp36, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_T0YPE) ;
statmp37 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp37)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp37, atslab_0, 25) ;
ats_selptrset_mac(anairiats_sum_2, statmp37, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_T0YPE) ;
statmp38 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp38)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp38, atslab_0, 7) ;
ats_selptrset_mac(anairiats_sum_2, statmp38, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEW) ;
statmp39 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp39)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp39, atslab_0, 15) ;
ats_selptrset_mac(anairiats_sum_2, statmp39, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEW) ;
statmp40 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp40)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp40, atslab_0, 31) ;
ats_selptrset_mac(anairiats_sum_2, statmp40, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEW) ;
statmp41 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp41)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp41, atslab_0, 2) ;
ats_selptrset_mac(anairiats_sum_2, statmp41, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEWTYPE) ;
statmp42 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp42)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp42, atslab_0, 10) ;
ats_selptrset_mac(anairiats_sum_2, statmp42, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEWTYPE) ;
statmp43 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp43)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp43, atslab_0, 26) ;
ats_selptrset_mac(anairiats_sum_2, statmp43, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEWTYPE) ;
statmp44 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp44)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp44, atslab_0, 3) ;
ats_selptrset_mac(anairiats_sum_2, statmp44, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEWT0YPE) ;
statmp45 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp45)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp45, atslab_0, 11) ;
ats_selptrset_mac(anairiats_sum_2, statmp45, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEWT0YPE) ;
statmp46 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp46)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp46, atslab_0, 27) ;
ats_selptrset_mac(anairiats_sum_2, statmp46, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_VIEWT0YPE) ;
statmp47 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)statmp47)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, statmp47, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp47, atslab_1, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_TYPES) ;
statmp48 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp48)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp48, atslab_0, statmp29) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop = statmp48 ;
statmp49 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp49)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp49, atslab_0, statmp30) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_pos, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_pos = statmp49 ;
statmp50 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp50)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp50, atslab_0, statmp31) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_neg, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_prop_neg = statmp50 ;
statmp51 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp51)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp51, atslab_0, statmp32) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type = statmp51 ;
statmp52 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp52)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp52, atslab_0, statmp33) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_pos, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_pos = statmp52 ;
statmp53 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp53)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp53, atslab_0, statmp34) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_neg, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_type_neg = statmp53 ;
statmp54 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp54)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp54, atslab_0, statmp35) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype = statmp54 ;
statmp55 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp55)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp55, atslab_0, statmp36) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_pos, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_pos = statmp55 ;
statmp56 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp56)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp56, atslab_0, statmp37) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_neg, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_t0ype_neg = statmp56 ;
statmp57 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp57)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp57, atslab_0, statmp38) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view = statmp57 ;
statmp58 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp58)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp58, atslab_0, statmp39) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_pos, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_pos = statmp58 ;
statmp59 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp59)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp59, atslab_0, statmp40) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_neg, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_view_neg = statmp59 ;
statmp60 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp60)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp60, atslab_0, statmp41) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype = statmp60 ;
statmp61 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp61)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp61, atslab_0, statmp42) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_pos, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_pos = statmp61 ;
statmp62 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp62)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp62, atslab_0, statmp43) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_neg, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vtype_neg = statmp62 ;
statmp63 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp63)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp63, atslab_0, statmp44) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype = statmp63 ;
statmp64 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp64)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp64, atslab_0, statmp45) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_pos, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_pos = statmp64 ;
statmp65 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp65)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp65, atslab_0, statmp46) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_neg, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_vt0ype_neg = statmp65 ;
statmp66 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)statmp66)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, statmp66, atslab_0, statmp47) ;
ATS_GC_MARKROOT(&_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_types, sizeof(ats_ptr_type)) ;
_2opt_2postiats_2src_2pats_staexp2_2esats__s2rt_types = statmp66 ;
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/opt/postiats/src/pats_staexp2_sort_dats.c] */
