/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-6-24: 22h:57m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .h files for avr */
#ifdef _ATS_AVR
#include "ats/basics.h"
#endif /* _ATS_AVR */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_rec_0 ;

typedef
struct {
ats_bool_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_rec_1 ;

/* external typedefs */
/* assuming abstract types */
/* sum constructor declarations */
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDmain_0) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDcase_exhaustiveness_1) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDtermet_isnat_2) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDtermet_isdec_3) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_fin_4) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_lvar_5) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_vbox_6) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDlstate_7) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDlstate_var_8) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDloop_9) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__H3YPOprop_0) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__H3YPObind_1) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__H3YPOeqeq_2) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRprop_0) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRitmlst_1) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMsvar_0) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMhypo_1) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMsVar_2) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMcnstr_3) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMcnstr_ref_4) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMdisj_5) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__LAMLPlam_0) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__LAMLPloop0_1) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__LAMLPloop1_2) ;
ATSglobal(ats_sum_type, _2opt_2postiats_2src_2pats_trans3_env_2esats__PFOBJ_0) ;

/* exn constructor declarations */
#ifdef _ATS_AVR

#define _2opt_2postiats_2src_2pats_trans3_env_2esats__staload() 

#else

/* static load function */

extern ats_void_type _2opt_2postiats_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_location_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_stamp_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_effect_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_patcst2_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_dynexp2_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_dynexp3_2esats__staload (void) ;

ats_void_type
_2opt_2postiats_2src_2pats_trans3_env_2esats__staload () {
static int _2opt_2postiats_2src_2pats_trans3_env_2esats__staload_flag = 0 ;
if (_2opt_2postiats_2src_2pats_trans3_env_2esats__staload_flag) return ;
_2opt_2postiats_2src_2pats_trans3_env_2esats__staload_flag = 1 ;

_2opt_2postiats_2src_2pats_basics_2esats__staload () ;
_2opt_2postiats_2src_2pats_location_2esats__staload () ;
_2opt_2postiats_2src_2pats_stamp_2esats__staload () ;
_2opt_2postiats_2src_2pats_effect_2esats__staload () ;
_2opt_2postiats_2src_2pats_staexp2_2esats__staload () ;
_2opt_2postiats_2src_2pats_staexp2_util_2esats__staload () ;
_2opt_2postiats_2src_2pats_patcst2_2esats__staload () ;
_2opt_2postiats_2src_2pats_dynexp2_2esats__staload () ;
_2opt_2postiats_2src_2pats_dynexp3_2esats__staload () ;

_2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDmain_0.tag = 0 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDcase_exhaustiveness_1.tag = 1 ;
_2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDtermet_isnat_2.tag = 2 ;
_2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDtermet_isdec_3.tag = 3 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_fin_4.tag = 4 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_lvar_5.tag = 5 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_vbox_6.tag = 6 ;
_2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDlstate_7.tag = 7 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDlstate_var_8.tag = 8 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRKINDloop_9.tag = 9 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__H3YPOprop_0.tag = 0 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__H3YPObind_1.tag = 1 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__H3YPOeqeq_2.tag = 2 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRprop_0.tag = 0 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__C3NSTRitmlst_1.tag = 1 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMsvar_0.tag = 0 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMhypo_1.tag = 1 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMsVar_2.tag = 2 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMcnstr_3.tag = 3 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMcnstr_ref_4.tag = 4 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__S3ITMdisj_5.tag = 5 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__LAMLPlam_0.tag = 0 ;
_2opt_2postiats_2src_2pats_trans3_env_2esats__LAMLPloop0_1.tag = 1 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__LAMLPloop1_2.tag = 2 ;
// _2opt_2postiats_2src_2pats_trans3_env_2esats__PFOBJ_0.tag = 0 ;
return ;
} /* staload function */


#endif/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/opt/postiats/src/pats_trans3_env_sats.c] */
