/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-6-24: 22h:57m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .h files for avr */
#ifdef _ATS_AVR
#include "ats/basics.h"
#endif /* _ATS_AVR */
/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_0 ;

typedef
struct {
ats_ptr_type atslab_e1xp_loc ;
ats_ptr_type atslab_e1xp_node ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_2 ;

typedef
struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_rec_3 ;

typedef struct {
ats_int_type atslab_0 ;
ats_uint_type atslab_1 ;
anairiats_rec_3 atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_sum_4 ;

typedef struct {
anairiats_rec_3 atslab_0 ;
} anairiats_sum_5 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__None_vt_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__Some_vt_1) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp1_2esats__E1XPstring_4) ;
ATSextern_val(ats_sum_type, _2opt_2postiats_2src_2pats_staexp1_2esats__E1XPnone_7) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2libats_2DATS_2linmap_avltree_2edats__B_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2libats_2DATS_2linmap_avltree_2edats__E_1) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_newline) () ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_sub_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_compare_uint_uint) (ats_uint_type, ats_uint_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_imax) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_size_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size_size) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_string) (ats_ptr_type) ;
ATSextern_val(ats_ptr_type, atspre_stropt_none) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_ATS_EXTERN_PREFIX) ;
ATSextern_fun(ats_uint_type, _2opt_2postiats_2src_2pats_symbol_2esats__symbol_get_stamp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_filename_2esats__filename_get_full) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_location_2esats__prerr_location) (ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2opt_2postiats_2src_2pats_location_2esats__location_dummy) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_fixity_2esats__fprint_fxty) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_symmap_2esats__symmap_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_make_nil) () ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_search) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_insert) (ats_ref_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pop) (ats_ref_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_push_nil) (ats_ref_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_savecur) (ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_restore) (ats_ref_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_localjoin) (ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pervasive_search) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pervasive_insert) (ats_ref_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pervasive_joinwth) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_symenv_2esats__fprint_symenv_map) (ats_ptr_type, ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp1_2esats__e1xp_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_staexp1_2esats__e1xp_none) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_add) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_find) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_pop) () ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_push_nil) () ;
ATSextern_fun(ats_ptr_type, _2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_pop) () ;
ATSextern_fun(ats_void_type, _2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_push_nil) () ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2opt_2postiats_2src_2pats_trans1_env_2esats__sasp__trans1_env_save_v = 0 ;
int _2opt_2postiats_2src_2pats_trans1_env_2esats__sasp__trans1_env_push_v = 0 ;
int _2opt_2postiats_2src_2pats_trans1_env_2esats__sasp__trans1_level_v = 0 ;
int _2opt_2postiats_2src_2pats_trans1_env_2esats__sasp__fxtyenv_push_v = 0 ;
int _2opt_2postiats_2src_2pats_trans1_env_2esats__sasp__e1xpenv_push_v = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type prerr_FILENAME_02077_ () ;
static
ats_void_type the_e1xpenv_localjoin_6 () ;
static
ats_void_type the_e1xpenv_save_7 () ;
static
ats_void_type the_e1xpenv_restore_8 () ;
static
ats_void_type prerr_warning1_loc_02086_ (ats_ptr_type arg0) ;
static
ats_void_type the_fxtyenv_localjoin_18 () ;
static
ats_void_type the_fxtyenv_save_20 () ;
static
ats_void_type the_fxtyenv_restore_21 () ;
static
ats_ptr_type ref_01264_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type linmap_make_nil_03487_ () ;
static
ats_int_type compare_key_key_03486_ats_uint_type (ats_uint_type arg0, ats_uint_type arg1, ats_clo_ref_type arg2) ;
static
ats_int_type avltree_height_01476_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0) ;
static
ats_ptr_type avltree_rrotate_01529_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_int_type arg3, ats_ptr_type arg4, ats_ptr_type arg5) ;
static
ats_ptr_type avltree_lrotate_01504_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_int_type arg3, ats_ptr_type arg4, ats_ptr_type arg5) ;
static
ats_bool_type insert_35 (ats_uint_type env0, ats_clo_ref_type env1, ats_ref_type arg0, anairiats_rec_3 arg1, ats_ref_type arg2) ;
static
ats_clo_ptr_type insert_35_closure_make (ats_uint_type env0, ats_clo_ref_type env1) ;
static
ats_bool_type insert_35_clofun (ats_clo_ptr_type cloptr, ats_ref_type arg0, anairiats_rec_3 arg1, ats_ref_type arg2) ;
static
ats_bool_type linmap_insert_03495_ats_uint_type_2canairiats_rec_3 (ats_ref_type arg0, ats_uint_type arg1, anairiats_rec_3 arg2, ats_clo_ref_type arg3, ats_ref_type arg4) ;
static
ats_ptr_type search_42 (ats_uint_type env0, ats_clo_ref_type env1, ats_ptr_type arg0) ;
static
ats_clo_ptr_type search_42_closure_make (ats_uint_type env0, ats_clo_ref_type env1) ;
static
ats_ptr_type search_42_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_ptr_type linmap_search_ref_03493_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0, ats_uint_type arg1, ats_clo_ref_type arg2) ;
static
ats_bool_type linmap_search_03492_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0, ats_uint_type arg1, ats_clo_ref_type arg2, ats_ref_type arg3) ;

/* partial value template declarations */
/* static temporary variable declarations */
ATSstatic (ats_ptr_type, statmp1) ;
ATSstatic (ats_ptr_type, statmp2) ;
// ATSstatic_void (statmp3) ;
// ATSstatic_void (statmp4) ;
ATSstatic (ats_ptr_type, statmp30) ;
ATSstatic (ats_ptr_type, statmp31) ;
// ATSstatic_void (statmp32) ;
// ATSstatic_void (statmp33) ;
ATSstatic (ats_int_type, statmp45) ;
// ATSstatic_void (statmp46) ;
// ATSstatic_void (statmp47) ;
ATSstatic (ats_ptr_type, statmp69) ;
ATSstatic (ats_ptr_type, statmp72) ;

/* external value variable declarations */

/* function implementations */

/*
// /opt/postiats/src/pats_trans1_env.dats: 1479(line=37, offs=28) -- 1510(line=37, offs=59)
*/
ATSstaticdec()
ats_void_type
prerr_FILENAME_02077_ () {
/* local vardec */
// ATSlocal_void (tmp0) ;

__ats_lab_prerr_FILENAME_02077_:
/* tmp0 = */ atspre_prerr_string (ATSstrcst("pats_trans1_staexp")) ;
return /* (tmp0) */ ;
} /* end of [prerr_FILENAME_02077_] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 2112(line=71, offs=3) -- 2192(line=74, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_add (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp5) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_add:
/* tmp5 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_insert (statmp2, arg0, arg1) ;
return /* (tmp5) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_add] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 2254(line=78, offs=3) -- 2344(line=81, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_addperv (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp6) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_addperv:
/* tmp6 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pervasive_insert (statmp2, arg0, arg1) ;
return /* (tmp6) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_addperv] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 2405(line=84, offs=18) -- 2579(line=91, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_find (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_find:
tmp8 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_search (statmp2, arg0) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (tmp8 == (ats_sum_ptr_type)0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp7 = tmp8 ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
// if (tmp8 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_1_1:
tmp7 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pervasive_search (statmp2, arg0) ;
break ;
} while (0) ;
return (tmp7) ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_find] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 2638(line=95, offs=3) -- 2749(line=99, offs=2)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_pop () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp9) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_pop:
tmp9 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pop (statmp2) ;
return (tmp9) ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_pop] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 2817(line=103, offs=3) -- 2925(line=107, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_push_nil () {
/* local vardec */
// ATSlocal_void (tmp10) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_push_nil:
/* tmp10 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_push_nil (statmp2) ;
return /* (tmp10) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_push_nil] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 2964(line=109, offs=5) -- 3175(line=118, offs=2)
*/
ATSstaticdec()
ats_void_type
the_e1xpenv_localjoin_6 () {
/* local vardec */
// ATSlocal_void (tmp11) ;

__ats_lab_the_e1xpenv_localjoin_6:
/* tmp11 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_localjoin (statmp2) ;
return /* (tmp11) */ ;
} /* end of [the_e1xpenv_localjoin_6] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 3247(line=122, offs=5) -- 3376(line=128, offs=4)
*/
ATSstaticdec()
ats_void_type
the_e1xpenv_save_7 () {
/* local vardec */
// ATSlocal_void (tmp12) ;

__ats_lab_the_e1xpenv_save_7:
/* tmp12 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_savecur (statmp2) ;
return /* (tmp12) */ ;
} /* end of [the_e1xpenv_save_7] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 3411(line=130, offs=5) -- 3594(line=137, offs=2)
*/
ATSstaticdec()
ats_void_type
the_e1xpenv_restore_8 () {
/* local vardec */
// ATSlocal_void (tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;

__ats_lab_the_e1xpenv_restore_8:
tmp14 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_restore (statmp2) ;
/* tmp13 = */ _2opt_2postiats_2src_2pats_symmap_2esats__symmap_free (tmp14) ;
return /* (tmp13) */ ;
} /* end of [the_e1xpenv_restore_8] */

/*
// /opt/postiats/src/pats_errmsg.dats: 2561(line=97, offs=20) -- 2622(line=100, offs=2)
*/
ATSstaticdec()
ats_void_type
prerr_warning1_loc_02086_ (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp21) ;
// ATSlocal_void (tmp22) ;

__ats_lab_prerr_warning1_loc_02086_:
/* tmp22 = */ _2opt_2postiats_2src_2pats_location_2esats__prerr_location (arg0) ;
/* tmp21 = */ atspre_prerr_string (ATSstrcst(": warning(1)")) ;
return /* (tmp21) */ ;
} /* end of [prerr_warning1_loc_02086_] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 3704(line=144, offs=23) -- 4291(line=171, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_get () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
// ATSlocal_void (tmp20) ;
ATSlocal (ats_ptr_type, tmp23) ;
// ATSlocal_void (tmp24) ;
// ATSlocal_void (tmp25) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_get:
tmp16 = _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_find (_2opt_2postiats_2src_2pats_symbol_2esats__symbol_ATS_EXTERN_PREFIX) ;
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (tmp16 == (ats_sum_ptr_type)0) { goto __ats_lab_6_0 ; }
__ats_lab_2_1:
tmp17 = ats_caselptrlab_mac(anairiats_sum_0, tmp16, atslab_0) ;
ATS_FREE(tmp16) ;
tmp18 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp17), atslab_e1xp_node) ;
do {
/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp18)->tag != 7) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp15 = atspre_stropt_none ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp18)->tag != 4) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp19 = ats_caselptrlab_mac(anairiats_sum_2, tmp18, atslab_0) ;
tmp15 = ats_castfn_mac(ats_ptr_type, tmp19) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
__ats_lab_5_1:
tmp23 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp17), atslab_e1xp_loc) ;
/* tmp20 = */ prerr_warning1_loc_02086_ (tmp23) ;
/* tmp24 = */ atspre_prerr_string (ATSstrcst(": a string definition is required for [ATS_EXTERN_PREFIX].")) ;
/* tmp25 = */ atspre_prerr_newline () ;
tmp15 = atspre_stropt_none ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
// if (tmp16 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_6_1:
tmp15 = atspre_stropt_none ;
break ;
} while (0) ;
return (tmp15) ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_get] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 4359(line=174, offs=23) -- 4509(line=179, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_set (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_set:
tmp27 = _2opt_2postiats_2src_2pats_staexp1_2esats__e1xp_string (_2opt_2postiats_2src_2pats_location_2esats__location_dummy, arg0) ;
/* tmp26 = */ _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_add (_2opt_2postiats_2src_2pats_symbol_2esats__symbol_ATS_EXTERN_PREFIX, tmp27) ;
return /* (tmp26) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_set] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 4582(line=182, offs=28) -- 4720(line=187, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_set_none () {
/* local vardec */
// ATSlocal_void (tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_set_none:
tmp29 = _2opt_2postiats_2src_2pats_staexp1_2esats__e1xp_none (_2opt_2postiats_2src_2pats_location_2esats__location_dummy) ;
/* tmp28 = */ _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_add (_2opt_2postiats_2src_2pats_symbol_2esats__symbol_ATS_EXTERN_PREFIX, tmp29) ;
return /* (tmp28) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_EXTERN_PREFIX_set_none] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 5037(line=203, offs=3) -- 5117(line=206, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_add (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp34) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_add:
/* tmp34 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_insert (statmp31, arg0, arg1) ;
return /* (tmp34) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_add] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 5174(line=209, offs=18) -- 5348(line=216, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_find (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_find:
tmp36 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_search (statmp31, arg0) ;
do {
/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (tmp36 == (ats_sum_ptr_type)0) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp35 = tmp36 ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
// if (tmp36 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_8_1:
tmp35 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pervasive_search (statmp31, arg0) ;
break ;
} while (0) ;
return (tmp35) ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_find] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 5408(line=219, offs=20) -- 5547(line=222, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__fprint_the_fxtyenv (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp37) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__fprint_the_fxtyenv:
/* tmp37 = */ _2opt_2postiats_2src_2pats_symenv_2esats__fprint_symenv_map (arg0, statmp31, &_2opt_2postiats_2src_2pats_fixity_2esats__fprint_fxty) ;
return /* (tmp37) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__fprint_the_fxtyenv] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 5608(line=226, offs=3) -- 5719(line=230, offs=2)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_pop () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp38) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_pop:
tmp38 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pop (statmp31) ;
return (tmp38) ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_pop] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 5787(line=234, offs=3) -- 5895(line=238, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_push_nil () {
/* local vardec */
// ATSlocal_void (tmp39) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_push_nil:
/* tmp39 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_push_nil (statmp31) ;
return /* (tmp39) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_push_nil] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 5934(line=240, offs=5) -- 6145(line=249, offs=2)
*/
ATSstaticdec()
ats_void_type
the_fxtyenv_localjoin_18 () {
/* local vardec */
// ATSlocal_void (tmp40) ;

__ats_lab_the_fxtyenv_localjoin_18:
/* tmp40 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_localjoin (statmp31) ;
return /* (tmp40) */ ;
} /* end of [the_fxtyenv_localjoin_18] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 6221(line=252, offs=31) -- 6297(line=254, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_pervasive_joinwth (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp41) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_pervasive_joinwth:
/* tmp41 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_pervasive_joinwth (statmp31, arg0) ;
return /* (tmp41) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_pervasive_joinwth] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 6351(line=258, offs=5) -- 6480(line=264, offs=4)
*/
ATSstaticdec()
ats_void_type
the_fxtyenv_save_20 () {
/* local vardec */
// ATSlocal_void (tmp42) ;

__ats_lab_the_fxtyenv_save_20:
/* tmp42 = */ _2opt_2postiats_2src_2pats_symenv_2esats__symenv_savecur (statmp31) ;
return /* (tmp42) */ ;
} /* end of [the_fxtyenv_save_20] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 6515(line=266, offs=5) -- 6698(line=273, offs=2)
*/
ATSstaticdec()
ats_void_type
the_fxtyenv_restore_21 () {
/* local vardec */
// ATSlocal_void (tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;

__ats_lab_the_fxtyenv_restore_21:
tmp44 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_restore (statmp31) ;
/* tmp43 = */ _2opt_2postiats_2src_2pats_symmap_2esats__symmap_free (tmp44) ;
return /* (tmp43) */ ;
} /* end of [the_fxtyenv_restore_21] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 7050(line=292, offs=22) -- 7109(line=294, offs=4)
*/
ATSglobaldec()
ats_int_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_get () {
/* local vardec */
ATSlocal (ats_int_type, tmp48) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_get:
tmp48 = ats_ptrget_mac(ats_int_type, (&statmp45)) ;
return (tmp48) ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_get] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 7175(line=297, offs=22) -- 7306(line=303, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_inc () {
/* local vardec */
// ATSlocal_void (tmp49) ;
ATSlocal (ats_int_type, tmp50) ;
ATSlocal (ats_int_type, tmp51) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_inc:
tmp51 = ats_ptrget_mac(ats_int_type, (&statmp45)) ;
tmp50 = atspre_add_int_int (tmp51, 1) ;
ats_ptrget_mac(ats_int_type, (&statmp45)) = tmp50 ;
return /* (tmp49) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_inc] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 7374(line=307, offs=3) -- 7508(line=311, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_dec () {
/* local vardec */
// ATSlocal_void (tmp52) ;
ATSlocal (ats_int_type, tmp53) ;
ATSlocal (ats_int_type, tmp54) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_dec:
tmp54 = ats_ptrget_mac(ats_int_type, (&statmp45)) ;
tmp53 = atspre_sub_int_int (tmp54, 1) ;
ats_ptrget_mac(ats_int_type, (&statmp45)) = tmp53 ;
return /* (tmp52) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_level_dec] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 7710(line=326, offs=3) -- 7930(line=332, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_pop () {
/* local vardec */
// ATSlocal_void (tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
// ATSlocal_void (tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_pop:
tmp56 = _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_pop () ;
/* tmp57 = */ _2opt_2postiats_2src_2pats_symmap_2esats__symmap_free (tmp56) ;
tmp58 = _2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_pop () ;
/* tmp55 = */ _2opt_2postiats_2src_2pats_symmap_2esats__symmap_free (tmp58) ;
return /* (tmp55) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_pop] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 7995(line=336, offs=3) -- 8147(line=340, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_push () {
/* local vardec */
// ATSlocal_void (tmp59) ;
// ATSlocal_void (tmp60) ;
// ATSlocal_void (tmp61) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_push:
/* tmp60 = */ _2opt_2postiats_2src_2pats_trans1_env_2esats__the_e1xpenv_push_nil () ;
/* tmp61 = ats_selsin_mac(tmp60, atslab_1) */ ;
/* tmp59 = */ _2opt_2postiats_2src_2pats_trans1_env_2esats__the_fxtyenv_push_nil () ;
return /* (tmp59) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_push] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 8217(line=344, offs=3) -- 8457(line=349, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_localjoin () {
/* local vardec */
// ATSlocal_void (tmp62) ;
// ATSlocal_void (tmp63) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_localjoin:
/* tmp63 = */ the_e1xpenv_localjoin_6 () ;
/* tmp62 = */ the_fxtyenv_localjoin_18 () ;
return /* (tmp62) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_localjoin] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 8662(line=363, offs=21) -- 8815(line=369, offs=4)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_save () {
/* local vardec */
// ATSlocal_void (tmp64) ;
// ATSlocal_void (tmp65) ;
// ATSlocal_void (tmp66) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_save:
/* tmp65 = */ the_e1xpenv_save_7 () ;
/* tmp66 = ats_selsin_mac(tmp65, atslab_1) */ ;
/* tmp64 = */ the_fxtyenv_save_20 () ;
return /* (tmp64) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_save] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 8884(line=373, offs=3) -- 9017(line=376, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_restore () {
/* local vardec */
// ATSlocal_void (tmp67) ;
// ATSlocal_void (tmp68) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_restore:
/* tmp68 = */ the_e1xpenv_restore_8 () ;
/* tmp67 = */ the_fxtyenv_restore_21 () ;
return /* (tmp67) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_restore] */

/*
// /opt/ats0210/prelude/DATS/reference.dats: 1828(line=57, offs=18) -- 1902(line=59, offs=4)
*/
ATSstaticdec()
ats_ptr_type
ref_01264_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;

__ats_lab_ref_01264_ats_ptr_type:
/* ats_ptr_type tmp71 ; */
tmp71 = arg0 ;
tmp70 = atspre_ref_make_elt_tsz ((&tmp71), sizeof(ats_ptr_type)) ;
return (tmp70) ;
} /* end of [ref_01264_ats_ptr_type] */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 2999(line=103, offs=29) -- 3008(line=103, offs=38)
*/
ATSstaticdec()
ats_ptr_type
linmap_make_nil_03487_ () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp73) ;

__ats_lab_linmap_make_nil_03487_:
tmp73 = (ats_sum_ptr_type)0 ;
return (tmp73) ;
} /* end of [linmap_make_nil_03487_] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 9525(line=396, offs=36) -- 9555(line=396, offs=66)
*/
ATSstaticdec()
ats_int_type
compare_key_key_03486_ats_uint_type (ats_uint_type arg0, ats_uint_type arg1, ats_clo_ref_type arg2) {
/* local vardec */
ATSlocal (ats_int_type, tmp74) ;

__ats_lab_compare_key_key_03486_ats_uint_type:
tmp74 = atspre_compare_uint_uint (arg0, arg1) ;
return (tmp74) ;
} /* end of [compare_key_key_03486_ats_uint_type] */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 3763(line=134, offs=24) -- 3870(line=135, offs=69)
*/
ATSstaticdec()
ats_int_type
avltree_height_01476_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp94) ;
ATSlocal (ats_int_type, tmp95) ;

__ats_lab_avltree_height_01476_ats_uint_type_2canairiats_rec_3:
do {
/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp95 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp94 = tmp95 ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_11_1:
tmp94 = 0 ;
break ;
} while (0) ;
return (tmp94) ;
} /* end of [avltree_height_01476_ats_uint_type_2canairiats_rec_3] */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 7399(line=276, offs=32) -- 8896(line=325, offs=4)
*/
ATSstaticdec()
ats_ptr_type
avltree_rrotate_01529_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_int_type arg3, ats_ptr_type arg4, ats_ptr_type arg5) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_int_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_int_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;
ATSlocal (ats_bool_type, tmp113) ;
ATSlocal (ats_int_type, tmp114) ;
ATSlocal (ats_int_type, tmp115) ;
ATSlocal (ats_ptr_type, tmp116) ;
ATSlocal (ats_int_type, tmp117) ;
ATSlocal (ats_int_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;
ATSlocal (ats_ptr_type, tmp121) ;
ATSlocal (ats_ptr_type, tmp122) ;
ATSlocal (ats_int_type, tmp123) ;
ATSlocal (ats_ptr_type, tmp124) ;
ATSlocal (ats_int_type, tmp125) ;
ATSlocal (ats_ptr_type, tmp126) ;
ATSlocal (ats_int_type, tmp127) ;
ATSlocal (ats_int_type, tmp128) ;
ATSlocal (ats_ptr_type, tmp129) ;
ATSlocal (ats_int_type, tmp130) ;
ATSlocal (ats_int_type, tmp131) ;
ATSlocal (ats_ptr_type, tmp132) ;

__ats_lab_avltree_rrotate_01529_ats_uint_type_2canairiats_rec_3:
tmp105 = ats_ptrget_mac(ats_ptr_type, arg2) ;
// if (tmp105 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp106 = &ats_caselptrlab_mac(anairiats_sum_4, tmp105, atslab_0) ;
tmp107 = &ats_caselptrlab_mac(anairiats_sum_4, tmp105, atslab_3) ;
tmp108 = &ats_caselptrlab_mac(anairiats_sum_4, tmp105, atslab_4) ;
tmp110 = ats_ptrget_mac(ats_ptr_type, tmp107) ;
tmp109 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp110) ;
tmp112 = ats_ptrget_mac(ats_ptr_type, tmp108) ;
tmp111 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp112) ;
tmp114 = atspre_iadd (tmp109, 0) ;
tmp113 = atspre_igte (tmp114, tmp111) ;
if (tmp113) {
tmp115 = atspre_iadd (tmp111, 1) ;
ats_ptrget_mac(ats_int_type, arg0) = tmp115 ;
tmp116 = ats_ptrget_mac(ats_ptr_type, tmp108) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp116 ;
tmp118 = atspre_imax (tmp109, tmp115) ;
tmp117 = atspre_iadd (1, tmp118) ;
ats_ptrget_mac(ats_int_type, tmp106) = tmp117 ;
ats_ptrget_mac(ats_ptr_type, tmp108) = arg5 ;
tmp104 = tmp105 ;
} else {
tmp119 = ats_ptrget_mac(ats_ptr_type, tmp108) ;
// if (tmp119 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp120 = &ats_caselptrlab_mac(anairiats_sum_4, tmp119, atslab_0) ;
tmp121 = &ats_caselptrlab_mac(anairiats_sum_4, tmp119, atslab_3) ;
tmp122 = &ats_caselptrlab_mac(anairiats_sum_4, tmp119, atslab_4) ;
tmp124 = ats_ptrget_mac(ats_ptr_type, tmp121) ;
tmp123 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp124) ;
tmp126 = ats_ptrget_mac(ats_ptr_type, tmp122) ;
tmp125 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp126) ;
tmp128 = atspre_imax (tmp125, arg3) ;
tmp127 = atspre_iadd (1, tmp128) ;
ats_ptrget_mac(ats_int_type, arg0) = tmp127 ;
tmp129 = ats_ptrget_mac(ats_ptr_type, tmp122) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp129 ;
tmp131 = atspre_imax (tmp109, tmp123) ;
tmp130 = atspre_iadd (1, tmp131) ;
ats_ptrget_mac(ats_int_type, tmp106) = tmp130 ;
tmp132 = ats_ptrget_mac(ats_ptr_type, tmp121) ;
ats_ptrget_mac(ats_ptr_type, tmp108) = tmp132 ;
ats_ptrget_mac(ats_int_type, tmp120) = arg1 ;
ats_ptrget_mac(ats_ptr_type, tmp121) = tmp105 ;
ats_ptrget_mac(ats_ptr_type, tmp122) = arg5 ;
tmp104 = tmp119 ;
} /* end of [if] */
return (tmp104) ;
} /* end of [avltree_rrotate_01529_ats_uint_type_2canairiats_rec_3] */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 5688(line=219, offs=32) -- 7215(line=268, offs=4)
*/
ATSstaticdec()
ats_ptr_type
avltree_lrotate_01504_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_int_type arg3, ats_ptr_type arg4, ats_ptr_type arg5) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp144) ;
ATSlocal (ats_ptr_type, tmp145) ;
ATSlocal (ats_ptr_type, tmp146) ;
ATSlocal (ats_ptr_type, tmp147) ;
ATSlocal (ats_ptr_type, tmp148) ;
ATSlocal (ats_int_type, tmp149) ;
ATSlocal (ats_ptr_type, tmp150) ;
ATSlocal (ats_int_type, tmp151) ;
ATSlocal (ats_ptr_type, tmp152) ;
ATSlocal (ats_bool_type, tmp153) ;
ATSlocal (ats_int_type, tmp154) ;
ATSlocal (ats_int_type, tmp155) ;
ATSlocal (ats_ptr_type, tmp156) ;
ATSlocal (ats_int_type, tmp157) ;
ATSlocal (ats_int_type, tmp158) ;
ATSlocal (ats_ptr_type, tmp159) ;
ATSlocal (ats_ptr_type, tmp160) ;
ATSlocal (ats_ptr_type, tmp161) ;
ATSlocal (ats_ptr_type, tmp162) ;
ATSlocal (ats_int_type, tmp163) ;
ATSlocal (ats_ptr_type, tmp164) ;
ATSlocal (ats_int_type, tmp165) ;
ATSlocal (ats_ptr_type, tmp166) ;
ATSlocal (ats_int_type, tmp167) ;
ATSlocal (ats_int_type, tmp168) ;
ATSlocal (ats_ptr_type, tmp169) ;
ATSlocal (ats_int_type, tmp170) ;
ATSlocal (ats_int_type, tmp171) ;
ATSlocal (ats_ptr_type, tmp172) ;

__ats_lab_avltree_lrotate_01504_ats_uint_type_2canairiats_rec_3:
tmp145 = ats_ptrget_mac(ats_ptr_type, arg4) ;
// if (tmp145 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp146 = &ats_caselptrlab_mac(anairiats_sum_4, tmp145, atslab_0) ;
tmp147 = &ats_caselptrlab_mac(anairiats_sum_4, tmp145, atslab_3) ;
tmp148 = &ats_caselptrlab_mac(anairiats_sum_4, tmp145, atslab_4) ;
tmp150 = ats_ptrget_mac(ats_ptr_type, tmp147) ;
tmp149 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp150) ;
tmp152 = ats_ptrget_mac(ats_ptr_type, tmp148) ;
tmp151 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp152) ;
tmp154 = atspre_iadd (tmp151, 0) ;
tmp153 = atspre_ilte (tmp149, tmp154) ;
if (tmp153) {
tmp155 = atspre_iadd (tmp149, 1) ;
ats_ptrget_mac(ats_int_type, arg0) = tmp155 ;
tmp156 = ats_ptrget_mac(ats_ptr_type, tmp147) ;
ats_ptrget_mac(ats_ptr_type, arg4) = tmp156 ;
tmp158 = atspre_imax (tmp155, tmp151) ;
tmp157 = atspre_iadd (1, tmp158) ;
ats_ptrget_mac(ats_int_type, tmp146) = tmp157 ;
ats_ptrget_mac(ats_ptr_type, tmp147) = arg5 ;
tmp144 = tmp145 ;
} else {
tmp159 = ats_ptrget_mac(ats_ptr_type, tmp147) ;
// if (tmp159 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp160 = &ats_caselptrlab_mac(anairiats_sum_4, tmp159, atslab_0) ;
tmp161 = &ats_caselptrlab_mac(anairiats_sum_4, tmp159, atslab_3) ;
tmp162 = &ats_caselptrlab_mac(anairiats_sum_4, tmp159, atslab_4) ;
tmp164 = ats_ptrget_mac(ats_ptr_type, tmp161) ;
tmp163 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp164) ;
tmp166 = ats_ptrget_mac(ats_ptr_type, tmp162) ;
tmp165 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp166) ;
tmp168 = atspre_imax (arg1, tmp163) ;
tmp167 = atspre_iadd (1, tmp168) ;
ats_ptrget_mac(ats_int_type, arg0) = tmp167 ;
tmp169 = ats_ptrget_mac(ats_ptr_type, tmp161) ;
ats_ptrget_mac(ats_ptr_type, arg4) = tmp169 ;
tmp171 = atspre_imax (tmp165, tmp151) ;
tmp170 = atspre_iadd (1, tmp171) ;
ats_ptrget_mac(ats_int_type, tmp146) = tmp170 ;
tmp172 = ats_ptrget_mac(ats_ptr_type, tmp162) ;
ats_ptrget_mac(ats_ptr_type, tmp147) = tmp172 ;
ats_ptrget_mac(ats_int_type, tmp160) = arg3 ;
ats_ptrget_mac(ats_ptr_type, tmp161) = arg5 ;
ats_ptrget_mac(ats_ptr_type, tmp162) = tmp145 ;
tmp144 = tmp159 ;
} /* end of [if] */
return (tmp144) ;
} /* end of [avltree_lrotate_01504_ats_uint_type_2canairiats_rec_3] */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 9017(line=333, offs=5) -- 11017(line=394, offs=4)
*/
ATSstaticdec()
ats_bool_type
insert_35 (ats_uint_type env0, ats_clo_ref_type env1, ats_ref_type arg0, anairiats_rec_3 arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_int_type, tmp89) ;
ATSlocal (ats_uint_type, tmp90) ;
ATSlocal (ats_bool_type, tmp91) ;
ATSlocal (ats_bool_type, tmp92) ;
ATSlocal (ats_int_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp96) ;
ATSlocal (ats_int_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_bool_type, tmp99) ;
ATSlocal (ats_int_type, tmp100) ;
ATSlocal (ats_int_type, tmp101) ;
ATSlocal (ats_int_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_bool_type, tmp133) ;
ATSlocal (ats_bool_type, tmp134) ;
ATSlocal (ats_int_type, tmp135) ;
ATSlocal (ats_ptr_type, tmp136) ;
ATSlocal (ats_int_type, tmp137) ;
ATSlocal (ats_ptr_type, tmp138) ;
ATSlocal (ats_bool_type, tmp139) ;
ATSlocal (ats_int_type, tmp140) ;
ATSlocal (ats_int_type, tmp141) ;
ATSlocal (ats_int_type, tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;
ATSlocal (anairiats_rec_3, tmp173) ;
ATSlocal (ats_ptr_type, tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;
ATSlocal (ats_ptr_type, tmp176) ;

__ats_lab_insert_35:
do {
/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (ats_ptrget_mac(ats_ptr_type, arg0) == (ats_sum_ptr_type)0) { goto __ats_lab_12_0 ; }
__ats_lab_9_1:
tmp84 = &ats_caselptrlab_mac(anairiats_sum_4, ats_ptrget_mac(ats_ptr_type, arg0), atslab_0) ;
tmp85 = &ats_caselptrlab_mac(anairiats_sum_4, ats_ptrget_mac(ats_ptr_type, arg0), atslab_1) ;
tmp86 = &ats_caselptrlab_mac(anairiats_sum_4, ats_ptrget_mac(ats_ptr_type, arg0), atslab_2) ;
tmp87 = &ats_caselptrlab_mac(anairiats_sum_4, ats_ptrget_mac(ats_ptr_type, arg0), atslab_3) ;
tmp88 = &ats_caselptrlab_mac(anairiats_sum_4, ats_ptrget_mac(ats_ptr_type, arg0), atslab_4) ;
tmp90 = ats_ptrget_mac(ats_uint_type, tmp85) ;
tmp89 = compare_key_key_03486_ats_uint_type (env0, tmp90, env1) ;
tmp91 = atspre_lt_int_int (tmp89, 0) ;
if (tmp91) {
tmp92 = insert_35 (env0, env1, tmp87, arg1, arg2) ;
tmp96 = ats_ptrget_mac(ats_ptr_type, tmp87) ;
tmp93 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp96) ;
tmp98 = ats_ptrget_mac(ats_ptr_type, tmp88) ;
tmp97 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp98) ;
tmp100 = atspre_isub (tmp93, tmp97) ;
tmp99 = atspre_ilte (tmp100, 1) ;
if (tmp99) {
tmp102 = atspre_imax (tmp93, tmp97) ;
tmp101 = atspre_iadd (1, tmp102) ;
ats_ptrget_mac(ats_int_type, tmp84) = tmp101 ;
tmp83 = tmp92 ;
} else {
tmp103 = avltree_rrotate_01529_ats_uint_type_2canairiats_rec_3 (tmp84, tmp93, tmp87, tmp97, tmp88, ats_ptrget_mac(ats_ptr_type, arg0)) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp103 ;
tmp83 = tmp92 ;
} /* end of [if] */
} else {
tmp133 = atspre_gt_int_int (tmp89, 0) ;
if (tmp133) {
tmp134 = insert_35 (env0, env1, tmp88, arg1, arg2) ;
tmp136 = ats_ptrget_mac(ats_ptr_type, tmp87) ;
tmp135 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp136) ;
tmp138 = ats_ptrget_mac(ats_ptr_type, tmp88) ;
tmp137 = avltree_height_01476_ats_uint_type_2canairiats_rec_3 (tmp138) ;
tmp140 = atspre_isub (tmp137, tmp135) ;
tmp139 = atspre_ilte (tmp140, 1) ;
if (tmp139) {
tmp142 = atspre_imax (tmp135, tmp137) ;
tmp141 = atspre_iadd (1, tmp142) ;
ats_ptrget_mac(ats_int_type, tmp84) = tmp141 ;
tmp83 = tmp134 ;
} else {
tmp143 = avltree_lrotate_01504_ats_uint_type_2canairiats_rec_3 (tmp84, tmp135, tmp87, tmp137, tmp88, ats_ptrget_mac(ats_ptr_type, arg0)) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp143 ;
tmp83 = tmp134 ;
} /* end of [if] */
} else {
tmp173 = ats_ptrget_mac(anairiats_rec_3, tmp86) ;
ats_ptrget_mac(anairiats_rec_3, arg2) = tmp173 ;
ats_ptrget_mac(anairiats_rec_3, tmp86) = arg1 ;
tmp83 = ats_true_bool ;
} /* end of [if] */
} /* end of [if] */
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
// if (ats_ptrget_mac(ats_ptr_type, arg0) != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_12_1:
tmp175 = (ats_sum_ptr_type)0 ;
tmp176 = (ats_sum_ptr_type)0 ;
tmp174 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
ats_selptrset_mac(anairiats_sum_4, tmp174, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_4, tmp174, atslab_1, env0) ;
ats_selptrset_mac(anairiats_sum_4, tmp174, atslab_2, arg1) ;
ats_selptrset_mac(anairiats_sum_4, tmp174, atslab_3, tmp175) ;
ats_selptrset_mac(anairiats_sum_4, tmp174, atslab_4, tmp176) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp174 ;
tmp83 = ats_false_bool ;
break ;
} while (0) ;
return (tmp83) ;
} /* end of [insert_35] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_uint_type closure_env_0 ;
ats_clo_ref_type closure_env_1 ;
} insert_35_closure_type ;

ats_bool_type
insert_35_clofun (ats_clo_ptr_type cloptr, ats_ref_type arg0, anairiats_rec_3 arg1, ats_ref_type arg2) {
return insert_35 (((insert_35_closure_type*)cloptr)->closure_env_0, ((insert_35_closure_type*)cloptr)->closure_env_1, arg0, arg1, arg2) ;
} /* end of function */

ATSinline()
ats_void_type
insert_35_closure_init (insert_35_closure_type *p_clo, ats_uint_type env0, ats_clo_ref_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&insert_35_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
insert_35_closure_make (ats_uint_type env0, ats_clo_ref_type env1) {
insert_35_closure_type *p_clo = ATS_MALLOC(sizeof(insert_35_closure_type)) ;
insert_35_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 8982(line=331, offs=3) -- 11072(line=400, offs=4)
*/
ATSstaticdec()
ats_bool_type
linmap_insert_03495_ats_uint_type_2canairiats_rec_3 (ats_ref_type arg0, ats_uint_type arg1, anairiats_rec_3 arg2, ats_clo_ref_type arg3, ats_ref_type arg4) {
/* local vardec */
ATSlocal (ats_bool_type, tmp82) ;

__ats_lab_linmap_insert_03495_ats_uint_type_2canairiats_rec_3:
tmp82 = insert_35 (arg1, arg3, arg0, arg2, arg4) ;
return (tmp82) ;
} /* end of [linmap_insert_03495_ats_uint_type_2canairiats_rec_3] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 9593(line=402, offs=3) -- 9928(line=412, offs=2)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__staload_file_insert (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_uint_type, tmp77) ;
ATSlocal (anairiats_rec_3, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (anairiats_rec_3, tmp80) ;
ATSlocal (ats_bool_type, tmp81) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__staload_file_insert:
tmp76 = _2opt_2postiats_2src_2pats_filename_2esats__filename_get_full (arg0) ;
tmp77 = _2opt_2postiats_2src_2pats_symbol_2esats__symbol_get_stamp (tmp76) ;
/* anairiats_rec_3 tmp78 ; */
tmp78.atslab_0 = arg1 ;
tmp78.atslab_1 = arg2 ;

tmp79 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp69), atslab_1) ;
/* anairiats_rec_3 tmp80 ; */
tmp81 = linmap_insert_03495_ats_uint_type_2canairiats_rec_3 (tmp79, tmp77, tmp78, ats_castfn_mac(ats_clo_ref_type, atspre_null_ptr), (&tmp80)) ;
return /* (tmp75) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__staload_file_insert] */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 4539(line=168, offs=7) -- 5104(line=188, offs=6)
*/
ATSstaticdec()
ats_ptr_type
search_42 (ats_uint_type env0, ats_clo_ref_type env1, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp186) ;
ATSlocal (ats_uint_type, tmp187) ;
ATSlocal (ats_ptr_type, tmp188) ;
ATSlocal (ats_ptr_type, tmp189) ;
ATSlocal (ats_ptr_type, tmp190) ;
ATSlocal (ats_int_type, tmp191) ;
ATSlocal (ats_bool_type, tmp192) ;
ATSlocal (ats_ptr_type, tmp193) ;
ATSlocal (ats_bool_type, tmp194) ;
ATSlocal (ats_ptr_type, tmp195) ;

__ats_lab_search_42:
do {
/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_17_0 ; }
__ats_lab_13_1:
tmp187 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp188 = &ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_2) ;
tmp189 = &ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_3) ;
tmp190 = &ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_4) ;
tmp191 = compare_key_key_03486_ats_uint_type (env0, tmp187, env1) ;
do {
/* branch: __ats_lab_14 */
__ats_lab_14_0:
__ats_lab_14_1:
tmp192 = atspre_lt_int_int (tmp191, 0) ;
if (!tmp192) { goto __ats_lab_15_1 ; }
tmp193 = ats_ptrget_mac(ats_ptr_type, tmp189) ;
arg0 = tmp193 ;
goto __ats_lab_search_42 ; // tail call
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
__ats_lab_15_1:
tmp194 = atspre_gt_int_int (tmp191, 0) ;
if (!tmp194) { goto __ats_lab_16_1 ; }
tmp195 = ats_ptrget_mac(ats_ptr_type, tmp190) ;
arg0 = tmp195 ;
goto __ats_lab_search_42 ; // tail call
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
__ats_lab_16_1:
tmp186 = tmp188 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_17_1:
tmp186 = atspre_null_ptr ;
break ;
} while (0) ;
return (tmp186) ;
} /* end of [search_42] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_uint_type closure_env_0 ;
ats_clo_ref_type closure_env_1 ;
} search_42_closure_type ;

ats_ptr_type
search_42_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return search_42 (((search_42_closure_type*)cloptr)->closure_env_0, ((search_42_closure_type*)cloptr)->closure_env_1, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
search_42_closure_init (search_42_closure_type *p_clo, ats_uint_type env0, ats_clo_ref_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&search_42_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
search_42_closure_make (ats_uint_type env0, ats_clo_ref_type env1) {
search_42_closure_type *p_clo = ATS_MALLOC(sizeof(search_42_closure_type)) ;
search_42_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 4499(line=167, offs=3) -- 5125(line=189, offs=2)
*/
ATSstaticdec()
ats_ptr_type
linmap_search_ref_03493_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0, ats_uint_type arg1, ats_clo_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp185) ;

__ats_lab_linmap_search_ref_03493_ats_uint_type_2canairiats_rec_3:
tmp185 = search_42 (arg1, arg2, arg0) ;
return (tmp185) ;
} /* end of [linmap_search_ref_03493_ats_uint_type_2canairiats_rec_3] */

/*
// /opt/ats0210/libats/DATS/linmap_avltree.dats: 4015(line=145, offs=3) -- 4431(line=162, offs=4)
*/
ATSstaticdec()
ats_bool_type
linmap_search_03492_ats_uint_type_2canairiats_rec_3 (ats_ptr_type arg0, ats_uint_type arg1, ats_clo_ref_type arg2, ats_ref_type arg3) {
/* local vardec */
ATSlocal (ats_bool_type, tmp183) ;
ATSlocal (ats_ptr_type, tmp184) ;
ATSlocal (ats_bool_type, tmp196) ;
ATSlocal (anairiats_rec_3, tmp197) ;

__ats_lab_linmap_search_03492_ats_uint_type_2canairiats_rec_3:
tmp184 = linmap_search_ref_03493_ats_uint_type_2canairiats_rec_3 (arg0, arg1, arg2) ;
tmp196 = atspre_pgt (tmp184, atspre_null_ptr) ;
if (tmp196) {
tmp197 = ats_ptrget_mac(anairiats_rec_3, tmp184) ;
ats_ptrget_mac(anairiats_rec_3, arg3) = tmp197 ;
tmp183 = ats_true_bool ;
} else {
tmp183 = ats_false_bool ;
} /* end of [if] */
return (tmp183) ;
} /* end of [linmap_search_03492_ats_uint_type_2canairiats_rec_3] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 9994(line=416, offs=3) -- 10418(line=432, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__staload_file_search (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp177) ;
ATSlocal (ats_ptr_type, tmp178) ;
ATSlocal (ats_uint_type, tmp179) ;
ATSlocal (ats_ptr_type, tmp180) ;
ATSlocal (anairiats_rec_3, tmp181) ;
ATSlocal (ats_bool_type, tmp182) ;
ATSlocal (ats_ptr_type, tmp198) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__staload_file_search:
tmp178 = _2opt_2postiats_2src_2pats_filename_2esats__filename_get_full (arg0) ;
tmp179 = _2opt_2postiats_2src_2pats_symbol_2esats__symbol_get_stamp (tmp178) ;
tmp180 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp69), atslab_1) ;
/* anairiats_rec_3 tmp181 ; */
tmp198 = ats_ptrget_mac(ats_ptr_type, tmp180) ;
tmp182 = linmap_search_03492_ats_uint_type_2canairiats_rec_3 (tmp198, tmp179, ats_castfn_mac(ats_clo_ref_type, atspre_null_ptr), (&tmp181)) ;
if (tmp182) {
tmp177 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp177, atslab_0, tmp181) ;
} else {
tmp177 = (ats_sum_ptr_type)0 ;
} /* end of [if] */
return (tmp177) ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__staload_file_search] */

/*
// /opt/postiats/src/pats_trans1_env.dats: 10597(line=441, offs=37) -- 10604(line=441, offs=44)
*/
ATSglobaldec()
ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_initialize () {
/* local vardec */
// ATSlocal_void (tmp199) ;

__ats_lab__2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_initialize:
return /* (tmp199) */ ;
} /* end of [_2opt_2postiats_2src_2pats_trans1_env_2esats__the_trans1_env_initialize] */

#ifdef _ATS_AVR

#define _2opt_2postiats_2src_2pats_trans1_env_2edats__staload() 

#else

/* static load function */

extern ats_void_type _2opt_2postiats_2src_2pats_errmsg_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_errmsg_2edats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_filename_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_fixity_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_symbol_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_symmap_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_symenv_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_staexp1_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_dynexp1_2esats__staload (void) ;
extern ats_void_type _2opt_2postiats_2src_2pats_trans1_env_2esats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e10_2libats_2SATS_2linmap_avltree_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2reference_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e10_2libats_2DATS_2linmap_avltree_2edats__staload (void) ;

ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2edats__staload () {
static int _2opt_2postiats_2src_2pats_trans1_env_2edats__staload_flag = 0 ;
if (_2opt_2postiats_2src_2pats_trans1_env_2edats__staload_flag) return ;
_2opt_2postiats_2src_2pats_trans1_env_2edats__staload_flag = 1 ;

_2opt_2postiats_2src_2pats_errmsg_2esats__staload () ;
_2opt_2postiats_2src_2pats_errmsg_2edats__staload () ;
_2opt_2postiats_2src_2pats_filename_2esats__staload () ;
_2opt_2postiats_2src_2pats_fixity_2esats__staload () ;
_2opt_2postiats_2src_2pats_symbol_2esats__staload () ;
_2opt_2postiats_2src_2pats_symmap_2esats__staload () ;
_2opt_2postiats_2src_2pats_symenv_2esats__staload () ;
_2opt_2postiats_2src_2pats_staexp1_2esats__staload () ;
_2opt_2postiats_2src_2pats_dynexp1_2esats__staload () ;
_2opt_2postiats_2src_2pats_trans1_env_2esats__staload () ;
// ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload () ;
// ATS_2d0_2e2_2e10_2libats_2SATS_2linmap_avltree_2esats__staload () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2reference_2edats__staload () ;
// ATS_2d0_2e2_2e10_2libats_2DATS_2linmap_avltree_2edats__staload () ;

return ;
} /* staload function */


#endif/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2opt_2postiats_2src_2pats_trans1_env_2edats__dynload_flag ;

ats_void_type
_2opt_2postiats_2src_2pats_trans1_env_2edats__dynload () {
_2opt_2postiats_2src_2pats_trans1_env_2edats__dynload_flag = 1 ;
_2opt_2postiats_2src_2pats_trans1_env_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */
ATS_GC_MARKROOT(&statmp1, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp2, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp30, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp31, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp45, sizeof(ats_int_type)) ;
ATS_GC_MARKROOT(&statmp69, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp72, sizeof(ats_ptr_type)) ;

/* marking external values for GC */

/* code for dynamic loading */
statmp1 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_make_nil () ;
statmp2 = ats_selsin_mac(statmp1, atslab_1) ;
/* statmp3 = */ atspre_vbox_make_view_ptr (statmp2) ;
/* statmp4 = ats_selsin_mac(statmp3, atslab_1) */ ;
statmp30 = _2opt_2postiats_2src_2pats_symenv_2esats__symenv_make_nil () ;
statmp31 = ats_selsin_mac(statmp30, atslab_1) ;
/* statmp32 = */ atspre_vbox_make_view_ptr (statmp31) ;
/* statmp33 = ats_selsin_mac(statmp32, atslab_1) */ ;
/* ats_int_type statmp45 ; */
statmp45 = 0 ;
/* statmp46 = */ atspre_vbox_make_view_ptr ((&statmp45)) ;
/* statmp47 = ats_selsin_mac(statmp46, atslab_1) */ ;
statmp72 = linmap_make_nil_03487_ () ;
statmp69 = ref_01264_ats_ptr_type (statmp72) ;
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/opt/postiats/src/pats_trans1_env_dats.c] */
